/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paginas_menu;

import java.awt.Color;
import java.awt.Component;

/**
 *
 * @author Daniel
 */
public class ver_info_de_pacientes extends javax.swing.JPanel {

    /**
     * Creates new form sacar_cita_pacientes
     */
    public ver_info_de_pacientes() {
        initComponents();
    }
    
    public void mostrar_panel(Component frame)
    {
        frame.setSize(620, 530);
        frame.setLocation(0,0); 
        Body.removeAll();
        Body.add(frame);
        Body.revalidate();
        Body.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        Panel_Emma = new javax.swing.JPanel();
        txt_Emma = new javax.swing.JLabel();
        Panel_Rosa = new javax.swing.JPanel();
        txt_Rosa = new javax.swing.JLabel();
        Panel_Isaac = new javax.swing.JPanel();
        txt_Isaac = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(620, 530));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Emma.setBackground(new java.awt.Color(64, 153, 167));
        Panel_Emma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Emma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_EmmaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_EmmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_EmmaMouseExited(evt);
            }
        });

        txt_Emma.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        txt_Emma.setForeground(new java.awt.Color(255, 255, 255));
        txt_Emma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Emma.setText("Emma");

        javax.swing.GroupLayout Panel_EmmaLayout = new javax.swing.GroupLayout(Panel_Emma);
        Panel_Emma.setLayout(Panel_EmmaLayout);
        Panel_EmmaLayout.setHorizontalGroup(
            Panel_EmmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EmmaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Emma, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_EmmaLayout.setVerticalGroup(
            Panel_EmmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Emma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Base.add(Panel_Emma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        Panel_Rosa.setBackground(new java.awt.Color(64, 153, 167));
        Panel_Rosa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Rosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_RosaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_RosaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_RosaMouseExited(evt);
            }
        });

        txt_Rosa.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        txt_Rosa.setForeground(new java.awt.Color(255, 255, 255));
        txt_Rosa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Rosa.setText("Rosa");

        javax.swing.GroupLayout Panel_RosaLayout = new javax.swing.GroupLayout(Panel_Rosa);
        Panel_Rosa.setLayout(Panel_RosaLayout);
        Panel_RosaLayout.setHorizontalGroup(
            Panel_RosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(Panel_RosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_RosaLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(txt_Rosa, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        Panel_RosaLayout.setVerticalGroup(
            Panel_RosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(Panel_RosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txt_Rosa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        Base.add(Panel_Rosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 210, 50));

        Panel_Isaac.setBackground(new java.awt.Color(64, 153, 167));
        Panel_Isaac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Isaac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_IsaacMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_IsaacMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_IsaacMouseExited(evt);
            }
        });

        txt_Isaac.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        txt_Isaac.setForeground(new java.awt.Color(255, 255, 255));
        txt_Isaac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Isaac.setText("Isaac");

        javax.swing.GroupLayout Panel_IsaacLayout = new javax.swing.GroupLayout(Panel_Isaac);
        Panel_Isaac.setLayout(Panel_IsaacLayout);
        Panel_IsaacLayout.setHorizontalGroup(
            Panel_IsaacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_IsaacLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(txt_Isaac, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_IsaacLayout.setVerticalGroup(
            Panel_IsaacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Isaac, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Base.add(Panel_Isaac, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 210, 50));

        add(Base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        Body.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        jLabel1.setText("Elija un paciente");

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addContainerGap(350, Short.MAX_VALUE))
        );

        add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 620, 480));
    }// </editor-fold>//GEN-END:initComponents
// Método que se activa al hacer clic en el panel asociado a la información de Emma
    private void Panel_EmmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_EmmaMouseClicked
        // Muestra la información del paciente Emma
        mostrar_panel(new sub_ver_info_de_pacientes("Emma"));
    }//GEN-LAST:event_Panel_EmmaMouseClicked
// Método que se activa al pasar el mouse sobre el panel de Emma
    private void Panel_EmmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_EmmaMouseEntered
        // Cambia el color de fondo del panel cuando el mouse se sitúa sobre él
        Color color1 = new Color (64,130,142);
        Panel_Emma.setBackground(color1);
    }//GEN-LAST:event_Panel_EmmaMouseEntered
// Método que se activa al salir el mouse del área del panel de Emma
    private void Panel_EmmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_EmmaMouseExited
        // Restaura el color de fondo original del panel cuando el mouse sale de él
        Color color2 = new Color (64,153,167);
        Panel_Emma.setBackground(color2);
    }//GEN-LAST:event_Panel_EmmaMouseExited

// Método que se activa al hacer clic en el panel asociado a la información de Rosa
    private void Panel_RosaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_RosaMouseClicked
        // Muestra la información del paciente Rosa
        mostrar_panel(new sub_ver_info_de_pacientes("Rosa"));
    }//GEN-LAST:event_Panel_RosaMouseClicked

// Método que se activa al pasar el mouse sobre el panel de Rosa    
    private void Panel_RosaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_RosaMouseEntered
        // Cambia el color de fondo del panel cuando el mouse se sitúa sobre él
        Color color1 = new Color (64,130,142);
        Panel_Rosa.setBackground(color1);
    }//GEN-LAST:event_Panel_RosaMouseEntered

    private void Panel_RosaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_RosaMouseExited
        Color color2 = new Color (64,153,167);
        Panel_Rosa.setBackground(color2);
    }//GEN-LAST:event_Panel_RosaMouseExited

    private void Panel_IsaacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_IsaacMouseClicked
        mostrar_panel(new sub_ver_info_de_pacientes("Isaac"));
    }//GEN-LAST:event_Panel_IsaacMouseClicked

    private void Panel_IsaacMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_IsaacMouseEntered
        Color color1 = new Color (64,130,142);
        Panel_Isaac.setBackground(color1);
    }//GEN-LAST:event_Panel_IsaacMouseEntered

    private void Panel_IsaacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_IsaacMouseExited
        Color color2 = new Color (64,153,167);
        Panel_Isaac.setBackground(color2);
    }//GEN-LAST:event_Panel_IsaacMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Panel_Emma;
    private javax.swing.JPanel Panel_Isaac;
    private javax.swing.JPanel Panel_Rosa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txt_Emma;
    private javax.swing.JLabel txt_Isaac;
    private javax.swing.JLabel txt_Rosa;
    // End of variables declaration//GEN-END:variables
}
