//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoULACIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int ID_Bitacora { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Numero_Placa { get; set; }
        public int ID_Movimiento { get; set; }
        public int ID_Parqueo { get; set; }
        public int ID_Tipo { get; set; }
    
        public virtual Movimiento Movimiento { get; set; }
        public virtual Parqueo Parqueo { get; set; }
        public virtual Tipo_Vehiculo Tipo_Vehiculo { get; set; }
    }
}
