//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoULACIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int ID_Usuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido_1 { get; set; }
        public string Apellido_2 { get; set; }
        public string Correo { get; set; }
        public string Contrasena { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Identificacion { get; set; }
        public string Numero_Carne { get; set; }
        public int ID_Rol { get; set; }
        public bool Estado { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
