/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paginas_menu;

import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Daniel
 */
public class cita_doctores extends javax.swing.JPanel {

    
    // Variables privadas de la clase para almacenar el nombre del doctor y su posición
    private String name;
    private String posicion = "doctor";
    
    /**
     * Constructor de la clase.
     * Inicializa la interfaz gráfica y establece el nombre del doctor.
     * @param name El nombre del doctor.
     */
     public cita_doctores(String name) {
        initComponents(); // Inicializa los componentes visuales
        this.name = name; // Establece el nombre del doctor recibido como parámetro
    }

    
    public void mostrar_panel(Component frame) {
        // Configuración del tamaño y la ubicación del componente dentro del panel
        frame.setSize(620, 530);
        frame.setLocation(0, 0); 
        
        // Elimina todos los componentes del panel actual
        Body.removeAll();
        
        // Agrega el nuevo componente al panel
        Body.add(frame);
        
        // Actualiza el panel para que muestre los cambios
        Body.revalidate();
        Body.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        Panel_Agendar = new javax.swing.JPanel();
        txt_Agendar = new javax.swing.JLabel();
        Panel_Ver = new javax.swing.JPanel();
        txt_Ver = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(620, 530));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Agendar.setBackground(new java.awt.Color(64, 153, 167));
        Panel_Agendar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Agendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_AgendarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_AgendarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_AgendarMouseExited(evt);
            }
        });

        txt_Agendar.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        txt_Agendar.setForeground(new java.awt.Color(255, 255, 255));
        txt_Agendar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Agendar.setText("Agendar Citas");

        javax.swing.GroupLayout Panel_AgendarLayout = new javax.swing.GroupLayout(Panel_Agendar);
        Panel_Agendar.setLayout(Panel_AgendarLayout);
        Panel_AgendarLayout.setHorizontalGroup(
            Panel_AgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_AgendarLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(txt_Agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel_AgendarLayout.setVerticalGroup(
            Panel_AgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_AgendarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_Agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Base.add(Panel_Agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        Panel_Ver.setBackground(new java.awt.Color(64, 153, 167));
        Panel_Ver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_VerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_VerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_VerMouseExited(evt);
            }
        });

        txt_Ver.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        txt_Ver.setForeground(new java.awt.Color(255, 255, 255));
        txt_Ver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Ver.setText("Mis citas");

        javax.swing.GroupLayout Panel_VerLayout = new javax.swing.GroupLayout(Panel_Ver);
        Panel_Ver.setLayout(Panel_VerLayout);
        Panel_VerLayout.setHorizontalGroup(
            Panel_VerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_VerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        Panel_VerLayout.setVerticalGroup(
            Panel_VerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Ver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Base.add(Panel_Ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 320, 50));

        add(Base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        Body.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        jLabel1.setText("Elija una opcion");

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(131, 131, 131))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 620, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void Panel_AgendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_AgendarMouseClicked
        mostrar_panel(new agendar_citas_doctores(name));
    }//GEN-LAST:event_Panel_AgendarMouseClicked

    private void Panel_AgendarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_AgendarMouseEntered
        Color color1 = new Color (64,130,142);
        Panel_Agendar.setBackground(color1);
    }//GEN-LAST:event_Panel_AgendarMouseEntered

    private void Panel_AgendarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_AgendarMouseExited
        Color color2 = new Color (64,153,167);
        Panel_Agendar.setBackground(color2);
    }//GEN-LAST:event_Panel_AgendarMouseExited

    private void Panel_VerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_VerMouseClicked
        try 
        {
            // Intenta mostrar el panel de citas para el doctor con nombre 'name'
            // Utiliza el método mostrar_panel y crea un nuevo objeto mis_citas con los parámetros name y posicion
            mostrar_panel(new mis_citas(name, posicion));
        } 
        catch (ParseException ex) 
        {
            // Si se produce una excepción del tipo ParseException, se captura y se registra la información detallada del error
            Logger.getLogger(cita_doctores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Netbeans nos sugirio poner el try catch para evitar errores
    }//GEN-LAST:event_Panel_VerMouseClicked

    private void Panel_VerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_VerMouseEntered
        Color color1 = new Color (64,130,142);
        Panel_Ver.setBackground(color1);
    }//GEN-LAST:event_Panel_VerMouseEntered

    private void Panel_VerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_VerMouseExited
        Color color2 = new Color (64,153,167);
        Panel_Ver.setBackground(color2);
    }//GEN-LAST:event_Panel_VerMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Panel_Agendar;
    private javax.swing.JPanel Panel_Ver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txt_Agendar;
    private javax.swing.JLabel txt_Ver;
    // End of variables declaration//GEN-END:variables
}
