/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paginas_menu;

import Info.citas_agendadas;
import java.text.ParseException;
import java.util.ArrayList;

/**
 *
 * @author Daniel
 */
public class mis_citas extends javax.swing.JPanel {

    // Variables para almacenar el nombre y la posición (doctor/paciente)
    private String nombre;
    private String posicion;

    /**
     * Constructor de la clase que muestra citas.
     * @param nombre Nombre del usuario actual.
     * @param posicion Posición del usuario ("doctor" o "paciente").
     * @throws ParseException Excepción lanzada si ocurre un error al analizar una fecha.
     */
    public mis_citas(String nombre, String posicion) throws ParseException {
        setLayout(null); // Establece un diseño nulo (se recomienda utilizar diseños de diseño de Java Swing)
        initComponents();
        this.nombre = nombre;
        this.posicion = posicion;

        // Verifica la posición del usuario para mostrar las citas correspondientes
        if (posicion.equals("doctor")) {
            // Recorre las citas y agrega citas para el doctor actual al panel correspondiente
            for (ArrayList<String> cita : citas_agendadas.getCitas()) {
                if (this.nombre.equals(cita.get(1))) {
                    Cita cita1 = new Cita(cita.get(1), posicion, cita.get(3), cita.get(6), cita.get(4), cita.get(5), panel_citas);
                    panel_citas.add(cita1); // Agrega la cita al panel
                    repaint(); // Actualiza la representación visual del panel
                    revalidate(); // Revalida el panel para que se muestren los cambios
                }
            }
        } else if (posicion.equals("paciente")) {
            // Recorre las citas y agrega citas para el paciente actual al panel correspondiente
            for (ArrayList<String> cita : citas_agendadas.getCitas()) {
                if (this.nombre.equals(cita.get(0))) {
                    Cita cita1 = new Cita(cita.get(0), posicion, cita.get(3), cita.get(6), cita.get(4), cita.get(5), panel_citas);
                    panel_citas.add(cita1); // Agrega la cita al panel
                    repaint(); // Actualiza la representación visual del panel
                    revalidate(); // Revalida el panel para que se muestren los cambios
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel_scrollbar = new javax.swing.JPanel();
        panel_citas = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panel_citas.setBackground(new java.awt.Color(255, 255, 255));
        panel_citas.setLayout(new javax.swing.BoxLayout(panel_citas, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout panel_scrollbarLayout = new javax.swing.GroupLayout(panel_scrollbar);
        panel_scrollbar.setLayout(panel_scrollbarLayout);
        panel_scrollbarLayout.setHorizontalGroup(
            panel_scrollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_citas, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        panel_scrollbarLayout.setVerticalGroup(
            panel_scrollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_citas, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel_scrollbar);

        titulo.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Mis citas");
        titulo.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_citas;
    private javax.swing.JPanel panel_scrollbar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
