/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paginas_menu;

import Info.doctor;
import frontend.Info_Cuentas;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author Daniel
 */
public class ver_datos_doctores extends javax.swing.JPanel {
    
    // Variable para almacenar el nombre del doctor
    private String nombre;

    /**
     * Constructor de la clase para ver los datos del doctor.
     * @param NOMBRE Nombre del doctor.
     */
    public ver_datos_doctores(String NOMBRE) {
        initComponents();
        this.nombre = NOMBRE;
        
        // Recorre la lista de cuentas para encontrar al doctor con el nombre proporcionado
        for (ArrayList<String> persona : Info_Cuentas.getCuentas()) {
            if(nombre.equals(persona.get(0))) {
                // Muestra los datos del doctor en los componentes de la interfaz gráfica
                Label_nombre.setText("Nombre: " + nombre);
                txt_field_contraseña.setText(persona.get(1));
                Label_correo.setText("Correo: " + persona.get(2));
                txt_field_cedula.setText(persona.get(3)); 
                txt_field_edad.setText(persona.get(4)); 
                txt_field_pais.setText(persona.get(5)); 
                txt_field_especialidad.setText(persona.get(7)); 
            }
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titulo = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        Label_contraseña = new javax.swing.JLabel();
        Label_correo = new javax.swing.JLabel();
        Label_cedula = new javax.swing.JLabel();
        Label_edad = new javax.swing.JLabel();
        Label_Pais = new javax.swing.JLabel();
        txt_field_cedula = new javax.swing.JTextField();
        txt_field_contraseña = new javax.swing.JTextField();
        txt_field_edad = new javax.swing.JTextField();
        Panel_boton = new javax.swing.JPanel();
        Label_boton = new javax.swing.JLabel();
        error_contraseña = new javax.swing.JLabel();
        error_cedula = new javax.swing.JLabel();
        error_edad = new javax.swing.JLabel();
        error_pais = new javax.swing.JLabel();
        Label_nombre = new javax.swing.JLabel();
        info_editada = new javax.swing.JLabel();
        Label_especialidad = new javax.swing.JLabel();
        txt_field_especialidad = new javax.swing.JTextField();
        txt_field_pais = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(620, 530));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_titulo.setText("Perfil");
        label_titulo.setToolTipText("");
        add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 350, -1));

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_contraseña.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_contraseña.setText("Contraseña: ");
        main_panel.add(Label_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        Label_correo.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_correo.setText("Correo:");
        main_panel.add(Label_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        Label_cedula.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_cedula.setText("Cedula:");
        main_panel.add(Label_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        Label_edad.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_edad.setText("Edad: ");
        main_panel.add(Label_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        Label_Pais.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_Pais.setText("Pais:");
        main_panel.add(Label_Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        txt_field_cedula.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        txt_field_cedula.setText("cedula");
        txt_field_cedula.setBorder(null);
        txt_field_cedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_cedulaMousePressed(evt);
            }
        });
        txt_field_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_field_cedulaKeyTyped(evt);
            }
        });
        main_panel.add(txt_field_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 400, 40));
        txt_field_cedula.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));

        txt_field_contraseña.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        txt_field_contraseña.setText("contraseña");
        txt_field_contraseña.setBorder(null);
        txt_field_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_contraseñaMousePressed(evt);
            }
        });
        main_panel.add(txt_field_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 350, 40));
        txt_field_contraseña.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));

        txt_field_edad.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        txt_field_edad.setText("edad");
        txt_field_edad.setBorder(null);
        txt_field_edad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_edadMousePressed(evt);
            }
        });
        txt_field_edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_field_edadKeyTyped(evt);
            }
        });
        main_panel.add(txt_field_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 420, 40));
        txt_field_edad.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));

        Panel_boton.setBackground(new java.awt.Color(64, 153, 167));
        Panel_boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_botonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_botonMouseExited(evt);
            }
        });

        Label_boton.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Label_boton.setForeground(new java.awt.Color(255, 255, 255));
        Label_boton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_boton.setText("Guardar Cambios");

        javax.swing.GroupLayout Panel_botonLayout = new javax.swing.GroupLayout(Panel_boton);
        Panel_boton.setLayout(Panel_botonLayout);
        Panel_botonLayout.setHorizontalGroup(
            Panel_botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_boton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        Panel_botonLayout.setVerticalGroup(
            Panel_botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_botonLayout.createSequentialGroup()
                .addComponent(Label_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        main_panel.add(Panel_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 160, 40));

        error_contraseña.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        error_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        error_contraseña.setText("La contraseña debe tener entre 5 y 20 caracteres");
        main_panel.add(error_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        error_cedula.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        error_cedula.setForeground(new java.awt.Color(255, 255, 255));
        error_cedula.setText("La cedula debe tener 9 caracteres");
        main_panel.add(error_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        error_edad.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        error_edad.setForeground(new java.awt.Color(255, 255, 255));
        error_edad.setText("La edad debe ser mayor a 1 y menor a 123");
        main_panel.add(error_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        error_pais.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        error_pais.setForeground(new java.awt.Color(255, 255, 255));
        error_pais.setText("El pais no existe");
        main_panel.add(error_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        Label_nombre.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_nombre.setText("Nombre: ");
        main_panel.add(Label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        info_editada.setBackground(new java.awt.Color(255, 255, 255));
        info_editada.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        info_editada.setForeground(new java.awt.Color(255, 255, 255));
        info_editada.setText("Informacion editada");
        main_panel.add(info_editada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 160, -1));

        Label_especialidad.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_especialidad.setText("Especialidad:");
        main_panel.add(Label_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        txt_field_especialidad.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        txt_field_especialidad.setText("especialidad");
        txt_field_especialidad.setBorder(null);
        txt_field_especialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_especialidadMousePressed(evt);
            }
        });
        txt_field_especialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_field_especialidadKeyTyped(evt);
            }
        });
        main_panel.add(txt_field_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 430, 40));
        txt_field_especialidad.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));

        txt_field_pais.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        txt_field_pais.setText("pais");
        txt_field_pais.setBorder(null);
        txt_field_pais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_paisMousePressed(evt);
            }
        });
        main_panel.add(txt_field_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 430, 40));
        txt_field_pais.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));

        add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 490, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_field_cedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_cedulaMousePressed
        error_cedula.setForeground(Color.white);
        info_editada.setForeground(Color.white);
    }//GEN-LAST:event_txt_field_cedulaMousePressed

    private void txt_field_contraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_contraseñaMousePressed
        error_contraseña.setForeground(Color.white);
        info_editada.setForeground(Color.white);
    }//GEN-LAST:event_txt_field_contraseñaMousePressed

    private void txt_field_edadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_edadMousePressed
        error_edad.setForeground(Color.white);
        info_editada.setForeground(Color.white);
    }//GEN-LAST:event_txt_field_edadMousePressed

    private void Panel_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_botonMouseEntered
        Color color1 = new Color (64,130,142);
        Panel_boton.setBackground(color1);
    }//GEN-LAST:event_Panel_botonMouseEntered

    private void Panel_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_botonMouseExited
        Color color2 = new Color (64,153,167);
        Panel_boton.setBackground(color2);
    }//GEN-LAST:event_Panel_botonMouseExited

    private void Panel_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_botonMouseClicked
        // Establece el color de las etiquetas de error y la información editada a blanco.
error_contraseña.setForeground(Color.white);
error_cedula.setForeground(Color.white);
error_edad.setForeground(Color.white);
error_pais.setForeground(Color.white);
info_editada.setForeground(Color.white);

// Se crea una instancia de la clase 'doctor' para editar los datos del doctor.
doctor editar = new doctor();
ArrayList<String> salida = new ArrayList<>();

// Se llama al método 'editar_datos' para actualizar la información del doctor.
// Se pasan como argumentos los nuevos valores de contraseña, correo, cédula, edad, país y especialidad.
salida = editar.editar_datos(this.nombre, txt_field_contraseña.getText(), Label_correo.getText(), txt_field_cedula.getText(), txt_field_edad.getText(), txt_field_pais.getText(), txt_field_especialidad.getText());

// Si la edición es correcta, se cambia el color del texto de 'info_editada' a verde.
if (salida.get(0).equals("correcto")) {
    info_editada.setForeground(new Color(0, 153, 0)); 
}

// Si el resultado indica que hay errores en la contraseña, se cambia el color del texto de 'error_contraseña' a rojo.
if (salida.get(1).equals("t")) {
    error_contraseña.setForeground(Color.red); 
}

// Si el resultado indica que hay errores en la cédula, se cambia el color del texto de 'error_cedula' a rojo.
if (salida.get(2).equals("t")) {
    error_cedula.setForeground(Color.red); 
}

// Si el resultado indica que hay errores en la edad, se cambia el color del texto de 'error_edad' a rojo.
if (salida.get(3).equals("t")) {
    error_edad.setForeground(Color.red); 
}

// Si el resultado indica que hay errores en el país, se cambia el color del texto de 'error_pais' a rojo.
if (salida.get(4).equals("t")) {
    error_pais.setForeground(Color.red); 
}
    }//GEN-LAST:event_Panel_botonMouseClicked

// Este método limita el ingreso de caracteres en un campo de texto a solo dígitos numéricos.
    private void txt_field_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_field_cedulaKeyTyped
        char c = evt.getKeyChar();
        // Consume el evento si el caracter ingresado no es un dígito del 0 al 9
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_field_cedulaKeyTyped
// Este método limita el ingreso de caracteres en un campo de texto a solo dígitos numéricos.
    private void txt_field_edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_field_edadKeyTyped
        char c = evt.getKeyChar();
        // Consume el evento si el caracter ingresado no es un dígito del 0 al 9
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_field_edadKeyTyped
// Este método limita el ingreso de caracteres en un campo de texto a solo letras (mayúsculas o minúsculas).
    private void txt_field_especialidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_field_especialidadKeyTyped
        char c = evt.getKeyChar();
        // Consume el evento si el caracter ingresado no es una letra (mayúscula o minúscula)
        if((c<'a' || c>'z') && (c<'A') | c>'Z') evt.consume();
    }//GEN-LAST:event_txt_field_especialidadKeyTyped

    private void txt_field_paisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_paisMousePressed
        error_pais.setForeground(Color.white);
        info_editada.setForeground(Color.white);
    }//GEN-LAST:event_txt_field_paisMousePressed

    private void txt_field_especialidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_especialidadMousePressed
        info_editada.setForeground(Color.white);
    }//GEN-LAST:event_txt_field_especialidadMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Pais;
    private javax.swing.JLabel Label_boton;
    private javax.swing.JLabel Label_cedula;
    private javax.swing.JLabel Label_contraseña;
    private javax.swing.JLabel Label_correo;
    private javax.swing.JLabel Label_edad;
    private javax.swing.JLabel Label_especialidad;
    private javax.swing.JLabel Label_nombre;
    private javax.swing.JPanel Panel_boton;
    private javax.swing.JLabel error_cedula;
    private javax.swing.JLabel error_contraseña;
    private javax.swing.JLabel error_edad;
    private javax.swing.JLabel error_pais;
    private javax.swing.JLabel info_editada;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField txt_field_cedula;
    private javax.swing.JTextField txt_field_contraseña;
    private javax.swing.JTextField txt_field_edad;
    private javax.swing.JTextField txt_field_especialidad;
    private javax.swing.JTextField txt_field_pais;
    // End of variables declaration//GEN-END:variables
}
