/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.awt.*;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import javax.swing.WindowConstants;

/**
 *
 * @author dylanrojas
 */
public class menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    int xMouse;
    int yMouse;
    private String name;
    
    public menu_principal() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        Cursor_drag.requestFocusInWindow();
        
        SetImageLabel(Imagen, "src\\Imagenes\\Imagen menu principal.jpg");
        SetImageLabel(Logo, "src\\Imagenes\\Imagen menu principal_Logo.png");
        SetImageLabel(Logo2, "src\\Imagenes\\Imagen menu principal_Logo2.png");
        SetImageLabel(img_minimizar, "src\\Imagenes\\-.png");
        SetImageLabel(img_cerrar, "src\\Imagenes\\x.png");
        SetImageLabel(Nombre_Hospital, "src\\Imagenes\\HOSPITAL_ULACIT.png");
    }

    public void initialize()
    {
        setTitle("Main Menu");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Bg = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Nombre_Hospital = new javax.swing.JLabel();
        img_cerrar = new javax.swing.JLabel();
        img_minimizar = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        Barra_arriba = new javax.swing.JPanel();
        Cursor_drag = new javax.swing.JTextField();
        Logo2 = new javax.swing.JLabel();
        Label_usuario = new javax.swing.JLabel();
        Label_iniciar_sesion = new javax.swing.JLabel();
        Separator_usuario = new javax.swing.JSeparator();
        Label_datos_incorrectos = new javax.swing.JLabel();
        Separator_contraseña = new javax.swing.JSeparator();
        txt_field_contraseña = new javax.swing.JPasswordField();
        Boton_iniciar_sesion = new javax.swing.JPanel();
        Label_boton_iniciar_sesion = new javax.swing.JLabel();
        txt_field_usuario = new javax.swing.JTextField();
        Label_contraseña = new javax.swing.JLabel();

        jLabel4.setText("continuar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen menu principal_Logo.png"))); // NOI18N
        Bg.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 140, 140));

        Nombre_Hospital.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        Nombre_Hospital.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Hospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HOSPITAL_ULACIT.png"))); // NOI18N
        Nombre_Hospital.setText("HOSPITAL ULACIT");
        Bg.add(Nombre_Hospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 230, 160));

        img_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png"))); // NOI18N
        img_cerrar.setText("jLabel1");
        img_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_cerrarMouseExited(evt);
            }
        });
        Bg.add(img_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 27, 25));

        img_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-.png"))); // NOI18N
        img_minimizar.setText("jLabel1");
        img_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_minimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_minimizarMouseExited(evt);
            }
        });
        Bg.add(img_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 27, 25));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen menu principal.jpg"))); // NOI18N
        Bg.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 390, 570));

        Barra_arriba.setBackground(new java.awt.Color(255, 255, 255));
        Barra_arriba.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barra_arribaMouseDragged(evt);
            }
        });
        Barra_arriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Barra_arribaMousePressed(evt);
            }
        });

        Cursor_drag.setEditable(false);
        Cursor_drag.setBackground(new java.awt.Color(255, 255, 255));
        Cursor_drag.setForeground(new java.awt.Color(255, 255, 255));
        Cursor_drag.setBorder(null);
        Cursor_drag.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout Barra_arribaLayout = new javax.swing.GroupLayout(Barra_arriba);
        Barra_arriba.setLayout(Barra_arribaLayout);
        Barra_arribaLayout.setHorizontalGroup(
            Barra_arribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_arribaLayout.createSequentialGroup()
                .addComponent(Cursor_drag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 836, Short.MAX_VALUE))
        );
        Barra_arribaLayout.setVerticalGroup(
            Barra_arribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_arribaLayout.createSequentialGroup()
                .addComponent(Cursor_drag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        Bg.add(Barra_arriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen menu principal_Logo2.png"))); // NOI18N
        Logo2.setText("jLabel1");
        Bg.add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, 60));

        Label_usuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        Label_usuario.setText("USUARIO");
        Bg.add(Label_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 280, 30));

        Label_iniciar_sesion.setFont(new java.awt.Font("Roboto Black", 1, 28)); // NOI18N
        Label_iniciar_sesion.setText("INICIAR SESIÓN");
        Bg.add(Label_iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 360, 40));

        Separator_usuario.setForeground(new java.awt.Color(0, 0, 0));
        Bg.add(Separator_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 380, 10));

        Label_datos_incorrectos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Label_datos_incorrectos.setForeground(new java.awt.Color(255, 255, 255));
        Label_datos_incorrectos.setText("Usuario y/o contraseña incorrectos");
        Bg.add(Label_datos_incorrectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 280, 30));

        Separator_contraseña.setForeground(new java.awt.Color(0, 0, 0));
        Bg.add(Separator_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 380, 10));

        txt_field_contraseña.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        txt_field_contraseña.setForeground(new java.awt.Color(204, 204, 204));
        txt_field_contraseña.setText("*************");
        txt_field_contraseña.setToolTipText("");
        txt_field_contraseña.setBorder(null);
        txt_field_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_contraseñaMousePressed(evt);
            }
        });
        Bg.add(txt_field_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 370, 30));

        Boton_iniciar_sesion.setBackground(new java.awt.Color(64, 157, 204));

        Label_boton_iniciar_sesion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Label_boton_iniciar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        Label_boton_iniciar_sesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_boton_iniciar_sesion.setText("Iniciar Sesion");
        Label_boton_iniciar_sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_boton_iniciar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Label_boton_iniciar_sesionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Boton_iniciar_sesionLayout = new javax.swing.GroupLayout(Boton_iniciar_sesion);
        Boton_iniciar_sesion.setLayout(Boton_iniciar_sesionLayout);
        Boton_iniciar_sesionLayout.setHorizontalGroup(
            Boton_iniciar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_boton_iniciar_sesion, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        Boton_iniciar_sesionLayout.setVerticalGroup(
            Boton_iniciar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_boton_iniciar_sesion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Bg.add(Boton_iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 130, 40));

        txt_field_usuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txt_field_usuario.setForeground(new java.awt.Color(204, 204, 204));
        txt_field_usuario.setText("Ingrese su nombre de usuario");
        txt_field_usuario.setBorder(null);
        txt_field_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_usuarioMousePressed(evt);
            }
        });
        Bg.add(txt_field_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 340, 30));

        Label_contraseña.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        Label_contraseña.setText("CONTRASEÑA");
        Bg.add(Label_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, 30));

        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Barra_arribaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_arribaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Barra_arribaMousePressed

    private void Barra_arribaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra_arribaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Barra_arribaMouseDragged

    private void img_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_img_cerrarMouseClicked

    private void img_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_cerrarMouseEntered
        img_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x_hover.png")));
        SetImageLabel(img_cerrar, "src\\Imagenes\\x_hover.png");
    }//GEN-LAST:event_img_cerrarMouseEntered

    private void img_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_cerrarMouseExited
        img_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png")));
        SetImageLabel(img_cerrar, "src\\Imagenes\\x.png");
    }//GEN-LAST:event_img_cerrarMouseExited

    private void img_minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_minimizarMouseEntered
        img_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-_hover.png")));
        SetImageLabel(img_minimizar, "src\\Imagenes\\-_hover.png");
    }//GEN-LAST:event_img_minimizarMouseEntered

    private void img_minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_minimizarMouseExited
        img_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-.png")));
        SetImageLabel(img_minimizar, "src\\Imagenes\\-.png");
    }//GEN-LAST:event_img_minimizarMouseExited

    private void img_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_minimizarMouseClicked
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_img_minimizarMouseClicked

    private void txt_field_contraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_contraseñaMousePressed
        Label_datos_incorrectos.setForeground(Color.white);
        if (String.valueOf(txt_field_contraseña.getPassword()).equals("*************")) {
            txt_field_contraseña.setText("");
            txt_field_contraseña.setForeground(Color.black);
        }
        if (txt_field_usuario.getText().isEmpty()) 
        {
            txt_field_usuario.setText("Ingrese su nombre de usuario");
            txt_field_usuario.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txt_field_contraseñaMousePressed

    private void Label_boton_iniciar_sesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_boton_iniciar_sesionMousePressed
        
        for (ArrayList<String> persona : Info_Cuentas.getCuentas()) 
        {
            if (txt_field_usuario.getText().equals(persona.get(0)) && String.valueOf(txt_field_contraseña.getPassword()).equals(persona.get(1)))
            { 
                this.name = persona.get(0);
                if (persona.get(6).equals("Paciente"))
                {
                    menu_pacientes menu_pacientes = new menu_pacientes(this.name);
                    menu_pacientes.initialize();
                    dispose();
                    return;
                }
                else if (persona.get(6).equals("Doctor"))
                {
                    menu_doctores menu_doctores = new menu_doctores(this.name);
                    menu_doctores.initialize();
                    dispose();
                    return;
                }
            }
        }
        Label_datos_incorrectos.setForeground(Color.red);
    }//GEN-LAST:event_Label_boton_iniciar_sesionMousePressed

    private void txt_field_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_usuarioMousePressed
        Label_datos_incorrectos.setForeground(Color.white);
        if (String.valueOf(txt_field_usuario.getText()).equals("Ingrese su nombre de usuario")) {
            txt_field_usuario.setText("");
            txt_field_usuario.setForeground(Color.black);
        }
        if (String.valueOf(txt_field_contraseña.getPassword()).isEmpty()) 
        {
            txt_field_contraseña.setText("*************");
            txt_field_contraseña.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txt_field_usuarioMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal().setVisible(true);
            }
        });
    }
    
    private void SetImageLabel (JLabel labelName, String root) 
    {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon( image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
        
    }

    public String getName() {
        return name;
    }
    
    

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra_arriba;
    private javax.swing.JPanel Bg;
    private javax.swing.JPanel Boton_iniciar_sesion;
    private javax.swing.JTextField Cursor_drag;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Label_boton_iniciar_sesion;
    private javax.swing.JLabel Label_contraseña;
    private javax.swing.JLabel Label_datos_incorrectos;
    private javax.swing.JLabel Label_iniciar_sesion;
    private javax.swing.JLabel Label_usuario;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel Nombre_Hospital;
    private javax.swing.JSeparator Separator_contraseña;
    private javax.swing.JSeparator Separator_usuario;
    private javax.swing.JLabel img_cerrar;
    private javax.swing.JLabel img_minimizar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txt_field_contraseña;
    private javax.swing.JTextField txt_field_usuario;
    // End of variables declaration//GEN-END:variables
}
