/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanels;

import java.awt.Color;
import java.util.ArrayList;
import proyecto.estructura.de.datos.Asegurado;
import proyecto.estructura.de.datos.Doctor;
import proyecto.estructura.de.datos.Info_Cuentas;

/**
 *
 * @author Daniel
 */
public class cajero2 extends javax.swing.JPanel {

    
    private static boolean ocupado = false; // Determina si el cajero esta ocupado o no
    private static Asegurado asegurado;

    public static Asegurado getAsegurado() {
        return asegurado;
    }

    public static void setAsegurado(Asegurado asegurado) {
        cajero2.asegurado = asegurado;
    }
    
    public static boolean isOcupado() {
        return ocupado;
    }

    public static void setOcupado(boolean ocupado) {
        cajero2.ocupado = ocupado;
    }
    /**
     * Constructor de la clase que recibe el nombre del paciente como parámetro.
     * Configura y muestra la información detallada del paciente en los componentes de la interfaz.
     */
    public cajero2() {
        initComponents();
        
        // Muestra la información específica del asegurado en diferentes componentes de texto
        if(asegurado!=null)
        {
            Label_nombre.setText("Nombre: " + asegurado.getNombre());
            Label_provincia.setText("Provincia: " + asegurado.getProvincia());
            Label_cedula.setText("Cedula: " + asegurado.getCedula()); 
            Label_edad.setText("Edad: " + asegurado.getEdad()); 
            Label_direccion.setText("Direccion: " + asegurado.getDireccion()); 
            Label_telefono.setText("Telefono: " + asegurado.getTelefono()); 
            if(ocupado)
            {
                Label_ocupado.setText("Hay una persona en el cajero");
            }
            else
            {
                Label_ocupado.setText("No hay nadie en el cajero");
            }
        }
        else
        {
            Label_nombre.setText("Nombre: ");
            Label_provincia.setText("Provincia: " );
            Label_cedula.setText("Cedula: " ); 
            Label_edad.setText("Edad: " ); 
            Label_direccion.setText("Direccion: " ); 
            Label_telefono.setText("Telefono: "); 
            if(ocupado)
            {
                Label_ocupado.setText("Hay una persona en el cajero");
            }
            else
            {
                Label_ocupado.setText("No hay nadie en el cajero");
            }
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Label_provincia = new javax.swing.JLabel();
        Label_cedula = new javax.swing.JLabel();
        Label_edad = new javax.swing.JLabel();
        Label_tipo_seguro = new javax.swing.JLabel();
        Label_direccion = new javax.swing.JLabel();
        panel_liberar_asegurado = new javax.swing.JPanel();
        liberar_asegurado_txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Label_nombre = new javax.swing.JLabel();
        Label_telefono = new javax.swing.JLabel();
        tipos_seguros = new javax.swing.JComboBox<>();
        Label_ocupado = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));

        Label_provincia.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_provincia.setText("Provincia:");

        Label_cedula.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_cedula.setText("Cedula:");

        Label_edad.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_edad.setText("Edad: ");

        Label_tipo_seguro.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_tipo_seguro.setText("Tipo de seguro:");

        Label_direccion.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_direccion.setText("Direccion:");

        panel_liberar_asegurado.setBackground(new java.awt.Color(64, 153, 167));
        panel_liberar_asegurado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_liberar_asegurado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_liberar_aseguradoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_liberar_aseguradoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_liberar_aseguradoMouseExited(evt);
            }
        });

        liberar_asegurado_txt.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        liberar_asegurado_txt.setForeground(new java.awt.Color(255, 255, 255));
        liberar_asegurado_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        liberar_asegurado_txt.setText("Liberar Asegurado");

        javax.swing.GroupLayout panel_liberar_aseguradoLayout = new javax.swing.GroupLayout(panel_liberar_asegurado);
        panel_liberar_asegurado.setLayout(panel_liberar_aseguradoLayout);
        panel_liberar_aseguradoLayout.setHorizontalGroup(
            panel_liberar_aseguradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(liberar_asegurado_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );
        panel_liberar_aseguradoLayout.setVerticalGroup(
            panel_liberar_aseguradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(liberar_asegurado_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel2.setText("Cajero 2");

        Label_nombre.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_nombre.setText("Nombre:");

        Label_telefono.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_telefono.setText("Telefono:");

        tipos_seguros.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        tipos_seguros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo 1", "Tipo 2", "Tipo 3", "Tipo 4" }));

        Label_ocupado.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_ocupado.setText("Ocupado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipos_seguros, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_ocupado))
                    .addComponent(Label_tipo_seguro)
                    .addComponent(panel_liberar_asegurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_nombre)
                            .addComponent(Label_direccion)
                            .addComponent(Label_telefono)
                            .addComponent(Label_edad)
                            .addComponent(Label_cedula)
                            .addComponent(Label_provincia))))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Label_ocupado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Label_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_cedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_edad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_provincia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_direccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_telefono)
                .addGap(42, 42, 42)
                .addComponent(Label_tipo_seguro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipos_seguros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_liberar_asegurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panel_liberar_aseguradoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_liberar_aseguradoMouseEntered
        Color color1 = new Color (64,130,142);
        panel_liberar_asegurado.setBackground(color1);
    }//GEN-LAST:event_panel_liberar_aseguradoMouseEntered

    private void panel_liberar_aseguradoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_liberar_aseguradoMouseExited
        Color color2 = new Color (64,153,167);
        panel_liberar_asegurado.setBackground(color2);
    }//GEN-LAST:event_panel_liberar_aseguradoMouseExited

    private void panel_liberar_aseguradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_liberar_aseguradoMouseClicked
        if (Integer.parseInt(this.asegurado.getEdad()) >= 60)
        {
            Info_Cuentas.getPilamayores().push(asegurado);
        }
        else
        {
            Info_Cuentas.getPilamenores().push(asegurado);
        }
        Doctor.asignar_doctor(asegurado);
        asegurado.getTipoSeguro().setDescripcionSeguro(tipos_seguros.getSelectedItem().toString());
        this.asegurado.setEnCajero(false);
        this.ocupado = false;
        this.asegurado = null;
        Info_Cuentas.setTotal_atendidos(Info_Cuentas.getTotal_atendidos()+1);
        if(!Info_Cuentas.getFila().ColaVacia())
        {
            this.asegurado = Info_Cuentas.getFila().getInicio().getDato();
            this.ocupado = true;
            this.asegurado.setEnCajero(true);
            Info_Cuentas.getFila().eliminar();
            Label_nombre.setText("Nombre: " + asegurado.getNombre());
            Label_provincia.setText("Provincia: " + asegurado.getProvincia());
            Label_cedula.setText("Cedula: " + asegurado.getCedula()); 
            Label_edad.setText("Edad: " + asegurado.getEdad()); 
            Label_direccion.setText("Direccion: " + asegurado.getDireccion()); 
            Label_telefono.setText("Telefono: " + asegurado.getTelefono()); 
            if(ocupado)
            {
                Label_ocupado.setText("Hay una persona en el cajero");
            }
            else
            {
                Label_ocupado.setText("No hay nadie en el cajero");
            }
        }
        else
        {
            Label_nombre.setText("Nombre: ");
            Label_provincia.setText("Provincia: " );
            Label_cedula.setText("Cedula: " ); 
            Label_edad.setText("Edad: " ); 
            Label_direccion.setText("Direccion: " ); 
            Label_telefono.setText("Telefono: "); 
            if(ocupado)
            {
                Label_ocupado.setText("Hay una persona en el cajero");
            }
            else
            {
                Label_ocupado.setText("No hay nadie en el cajero");
            }
        }
    }//GEN-LAST:event_panel_liberar_aseguradoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_cedula;
    private javax.swing.JLabel Label_direccion;
    private javax.swing.JLabel Label_edad;
    private javax.swing.JLabel Label_nombre;
    private javax.swing.JLabel Label_ocupado;
    private javax.swing.JLabel Label_provincia;
    private javax.swing.JLabel Label_telefono;
    private javax.swing.JLabel Label_tipo_seguro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel liberar_asegurado_txt;
    private javax.swing.JPanel panel_liberar_asegurado;
    private javax.swing.JComboBox<String> tipos_seguros;
    // End of variables declaration//GEN-END:variables
}
