/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanels;

import JFrames.Inicio_Sesion;
import JFrames.menu_asegurados;
import java.awt.Color;
import proyecto.estructura.de.datos.Asegurado;
import proyecto.estructura.de.datos.Info_Cuentas;

/**
 *
 * @author Daniel
 */
public class crear_ticket extends javax.swing.JPanel {

    private Inicio_Sesion ventana;
    
    /**
     * Creates new form crear_ticket
     */
    public crear_ticket(Inicio_Sesion ventana) {
        initComponents();
        this.ventana = ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_crear_ticket = new javax.swing.JPanel();
        Label_boton_iniciar_sesion = new javax.swing.JLabel();
        ya_tiene = new javax.swing.JLabel();
        txt_field_cedula = new javax.swing.JTextField();
        Separator_cedula = new javax.swing.JSeparator();
        Boton_ingresar = new javax.swing.JPanel();
        Label_boton_ingresar = new javax.swing.JLabel();
        Label_datos_incorrectos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        Boton_crear_ticket.setBackground(new java.awt.Color(64, 157, 204));
        Boton_crear_ticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_crear_ticketMouseClicked(evt);
            }
        });

        Label_boton_iniciar_sesion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Label_boton_iniciar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        Label_boton_iniciar_sesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_boton_iniciar_sesion.setText("Crear Ticket");
        Label_boton_iniciar_sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout Boton_crear_ticketLayout = new javax.swing.GroupLayout(Boton_crear_ticket);
        Boton_crear_ticket.setLayout(Boton_crear_ticketLayout);
        Boton_crear_ticketLayout.setHorizontalGroup(
            Boton_crear_ticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_boton_iniciar_sesion, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        Boton_crear_ticketLayout.setVerticalGroup(
            Boton_crear_ticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Boton_crear_ticketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_boton_iniciar_sesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ya_tiene.setFont(new java.awt.Font("Roboto Light", 1, 23)); // NOI18N
        ya_tiene.setText("CEDULA:");
        ya_tiene.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ya_tiene.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ya_tieneMousePressed(evt);
            }
        });

        txt_field_cedula.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txt_field_cedula.setForeground(new java.awt.Color(204, 204, 204));
        txt_field_cedula.setText("Ingrese su cedula");
        txt_field_cedula.setBorder(null);
        txt_field_cedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_cedulaMousePressed(evt);
            }
        });
        txt_field_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_field_cedulaKeyTyped(evt);
            }
        });

        Separator_cedula.setForeground(new java.awt.Color(0, 0, 0));

        Boton_ingresar.setBackground(new java.awt.Color(64, 157, 204));

        Label_boton_ingresar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Label_boton_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Label_boton_ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_boton_ingresar.setText("Ingresar");
        Label_boton_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_boton_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Label_boton_ingresarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Boton_ingresarLayout = new javax.swing.GroupLayout(Boton_ingresar);
        Boton_ingresar.setLayout(Boton_ingresarLayout);
        Boton_ingresarLayout.setHorizontalGroup(
            Boton_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_boton_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        Boton_ingresarLayout.setVerticalGroup(
            Boton_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_boton_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Label_datos_incorrectos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Label_datos_incorrectos.setForeground(new java.awt.Color(255, 255, 255));
        Label_datos_incorrectos.setText("Cedula incorrecta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_field_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Separator_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Label_datos_incorrectos, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(118, Short.MAX_VALUE))
                    .addComponent(ya_tiene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Boton_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Boton_crear_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ya_tiene, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_field_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Separator_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_datos_incorrectos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Boton_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_crear_ticket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ya_tieneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ya_tieneMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ya_tieneMousePressed

    private void txt_field_cedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_cedulaMousePressed
        Label_datos_incorrectos.setForeground(Color.white);
        if (String.valueOf(txt_field_cedula.getText()).equals("Ingrese su cedula")) {
            txt_field_cedula.setText("");
            txt_field_cedula.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_field_cedulaMousePressed

    private void Label_boton_ingresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_boton_ingresarMousePressed
        try
        {
            if(Info_Cuentas.getFila().Buscar(String.valueOf(txt_field_cedula.getText())) != null)
            {
                menu_asegurados menu_asegurados = new menu_asegurados(String.valueOf(txt_field_cedula.getText()), Info_Cuentas.getFila().Buscar(String.valueOf(txt_field_cedula.getText())));
                menu_asegurados.initialize();
                ventana.dispose();
            }
            else if (cajero1.getAsegurado().getCedula().equals(String.valueOf(txt_field_cedula.getText())))
            {
                menu_asegurados menu_asegurados = new menu_asegurados(String.valueOf(txt_field_cedula.getText()), cajero1.getAsegurado());
                menu_asegurados.initialize();
                ventana.dispose();
            }
            else if (cajero2.getAsegurado().getCedula().equals(String.valueOf(txt_field_cedula.getText())))
            {
                menu_asegurados menu_asegurados = new menu_asegurados(String.valueOf(txt_field_cedula.getText()), cajero2.getAsegurado());
                menu_asegurados.initialize();
                ventana.dispose();
            }
            else if (cajero3.getAsegurado().getCedula().equals(String.valueOf(txt_field_cedula.getText())))
            {
                menu_asegurados menu_asegurados = new menu_asegurados(String.valueOf(txt_field_cedula.getText()), cajero3.getAsegurado());
                menu_asegurados.initialize();
                ventana.dispose();
            }
            else
            {
                Label_datos_incorrectos.setText("La cedula no existe o ya fue antendido");
                Label_datos_incorrectos.setForeground(Color.red);
            }
        }
        catch(Exception e)
        {
            Label_datos_incorrectos.setText("La cedula no existe o ya fue antendido");
            Label_datos_incorrectos.setForeground(Color.red);
        }
    }//GEN-LAST:event_Label_boton_ingresarMousePressed

    private void Boton_crear_ticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_crear_ticketMouseClicked
        if (String.valueOf(txt_field_cedula.getText()).length() == 9)
        {
            Asegurado asegurado = new Asegurado(String.valueOf(txt_field_cedula.getText()), "", "", "", "", "");
            Info_Cuentas.getFila().cola_asegurados(asegurado);
            menu_asegurados menu_asegurados = new menu_asegurados(String.valueOf(txt_field_cedula.getText()), asegurado);
            menu_asegurados.initialize();
            ventana.dispose();
        }
        else
        {
            Label_datos_incorrectos.setText("La cedula debe tener 9 digitos");
            Label_datos_incorrectos.setForeground(Color.red);
        }
    }//GEN-LAST:event_Boton_crear_ticketMouseClicked

    private void txt_field_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_field_cedulaKeyTyped
        char c = evt.getKeyChar();
        // Consume el evento si el caracter ingresado no es un dígito del 0 al 9
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_field_cedulaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Boton_crear_ticket;
    private javax.swing.JPanel Boton_ingresar;
    private javax.swing.JLabel Label_boton_ingresar;
    private javax.swing.JLabel Label_boton_iniciar_sesion;
    private javax.swing.JLabel Label_datos_incorrectos;
    private javax.swing.JSeparator Separator_cedula;
    private javax.swing.JTextField txt_field_cedula;
    private javax.swing.JLabel ya_tiene;
    // End of variables declaration//GEN-END:variables
}
