/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanels;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import proyecto.estructura.de.datos.Asegurado;
import proyecto.estructura.de.datos.Info_Cuentas;

/**
 *
 * @author Daniel
 */
public class datos_mayores60 extends javax.swing.JPanel {

    private Asegurado asegurado;

    public Asegurado getAsegurado() {
        return asegurado;
    }

    public void setAsegurado(Asegurado asegurado) {
        this.asegurado = asegurado;
    }
    
    /**
     * Constructor de la clase que recibe el nombre del paciente como parámetro.
     * Configura y muestra la información detallada del paciente en los componentes de la interfaz.
     */
    public datos_mayores60(Asegurado asegurado) {
        initComponents();
        this.asegurado = asegurado;
        Label_pariente.setText("Nombre: " );
        Label_telefono.setText("Telefono: " ); 
        txt_field_pariente.setText("Ingrese el nombre de su pariente"); 
        txt_field_telefono_pariente.setText("Ingrese el teléfono de su pariente"); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        Label_pariente = new javax.swing.JLabel();
        Label_telefono = new javax.swing.JLabel();
        txt_field_pariente = new javax.swing.JTextField();
        txt_field_telefono_pariente = new javax.swing.JTextField();
        Panel_boton = new javax.swing.JPanel();
        Label_boton = new javax.swing.JLabel();
        info_editada = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        titulo.setText("Debe digitar lo siguiente ya que es");

        Label_pariente.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_pariente.setText("Pariente:");

        Label_telefono.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_telefono.setText("Telefono del pariente:");

        txt_field_pariente.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        txt_field_pariente.setForeground(new java.awt.Color(204, 204, 204));
        txt_field_pariente.setText("contraseña");
        txt_field_pariente.setBorder(null);
        txt_field_pariente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_parienteMousePressed(evt);
            }
        });

        txt_field_telefono_pariente.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        txt_field_telefono_pariente.setForeground(new java.awt.Color(204, 204, 204));
        txt_field_telefono_pariente.setText("contraseña");
        txt_field_telefono_pariente.setBorder(null);
        txt_field_telefono_pariente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_telefono_parienteMousePressed(evt);
            }
        });
        txt_field_telefono_pariente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_field_telefono_parienteKeyTyped(evt);
            }
        });

        Panel_boton.setBackground(new java.awt.Color(64, 153, 167));
        Panel_boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_botonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_botonMouseExited(evt);
            }
        });

        Label_boton.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Label_boton.setForeground(new java.awt.Color(255, 255, 255));
        Label_boton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_boton.setText("Guardar cambios");

        javax.swing.GroupLayout Panel_botonLayout = new javax.swing.GroupLayout(Panel_boton);
        Panel_boton.setLayout(Panel_botonLayout);
        Panel_botonLayout.setHorizontalGroup(
            Panel_botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_boton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        Panel_botonLayout.setVerticalGroup(
            Panel_botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_botonLayout.createSequentialGroup()
                .addComponent(Label_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        info_editada.setBackground(new java.awt.Color(255, 255, 255));
        info_editada.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        info_editada.setForeground(new java.awt.Color(255, 255, 255));
        info_editada.setText("Informacion editada");

        titulo2.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        titulo2.setText("una persona mayor de 60 años");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_boton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(info_editada, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_pariente)
                        .addGap(25, 25, 25)
                        .addComponent(txt_field_pariente, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_telefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_field_telefono_pariente, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_pariente)
                    .addComponent(txt_field_pariente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_telefono)
                    .addComponent(txt_field_telefono_pariente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(Panel_boton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(info_editada)))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_field_parienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_parienteMousePressed
        if (String.valueOf(txt_field_pariente.getText()).equals("Ingrese el nombre de su pariente")) {
            txt_field_pariente.setText("");
            txt_field_pariente.setForeground(Color.black);
        }

        else if (String.valueOf(txt_field_telefono_pariente.getText()).isEmpty()) {
            txt_field_telefono_pariente.setText("Ingrese el teléfono de su pariente");
            txt_field_telefono_pariente.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txt_field_parienteMousePressed

    private void txt_field_telefono_parienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_telefono_parienteMousePressed
        if (String.valueOf(txt_field_telefono_pariente.getText()).equals("Ingrese el teléfono de su pariente")) {
            txt_field_telefono_pariente.setText("");
            txt_field_telefono_pariente.setForeground(Color.black);
        }

        if (String.valueOf(txt_field_pariente.getText()).isEmpty()) {
            txt_field_pariente.setText("Ingrese el nombre de su pariente");
            txt_field_pariente.setForeground(new Color(204, 204, 204));
        }

    }//GEN-LAST:event_txt_field_telefono_parienteMousePressed

    private void Panel_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_botonMouseClicked
        asegurado.setPariente(String.valueOf(txt_field_pariente.getText()));
        asegurado.setTelpariente(String.valueOf(txt_field_telefono_pariente.getText()));
        info_editada.setForeground(new Color(0,153,0));
    }//GEN-LAST:event_Panel_botonMouseClicked

    private void Panel_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_botonMouseEntered
        Color color1 = new Color (64,130,142);
        Panel_boton.setBackground(color1);
    }//GEN-LAST:event_Panel_botonMouseEntered

    private void Panel_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_botonMouseExited
        Color color2 = new Color (64,153,167);
        Panel_boton.setBackground(color2);
    }//GEN-LAST:event_Panel_botonMouseExited

    private void txt_field_telefono_parienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_field_telefono_parienteKeyTyped
        char c = evt.getKeyChar();
        // Consume el evento si el caracter ingresado no es un dígito del 0 al 9
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_field_telefono_parienteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_boton;
    private javax.swing.JLabel Label_pariente;
    private javax.swing.JLabel Label_telefono;
    private javax.swing.JPanel Panel_boton;
    private javax.swing.JLabel info_editada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo2;
    private javax.swing.JTextField txt_field_pariente;
    private javax.swing.JTextField txt_field_telefono_pariente;
    // End of variables declaration//GEN-END:variables
}
