/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanels;

import java.awt.Color;
import java.awt.Component;

/**
 *
 * @author Daniel
 */
public class menu_cajeros extends javax.swing.JPanel {

    /**
     * Creates new form sacar_cita_pacientes
     */
    public menu_cajeros() {
        initComponents();
    }
    
    public void mostrar_panel(Component frame)
    {
        frame.setSize(620, 530);
        frame.setLocation(0,0); 
        Body.removeAll();
        Body.add(frame);
        Body.revalidate();
        Body.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        Panel_cajero1 = new javax.swing.JPanel();
        txt_cajero1 = new javax.swing.JLabel();
        Panel_cajero2 = new javax.swing.JPanel();
        txt_cajero2 = new javax.swing.JLabel();
        Panel_cajero3 = new javax.swing.JPanel();
        txt_cajero3 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(620, 530));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_cajero1.setBackground(new java.awt.Color(64, 153, 167));
        Panel_cajero1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_cajero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_cajero1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_cajero1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_cajero1MouseExited(evt);
            }
        });

        txt_cajero1.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        txt_cajero1.setForeground(new java.awt.Color(255, 255, 255));
        txt_cajero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_cajero1.setText("Cajero 1");

        javax.swing.GroupLayout Panel_cajero1Layout = new javax.swing.GroupLayout(Panel_cajero1);
        Panel_cajero1.setLayout(Panel_cajero1Layout);
        Panel_cajero1Layout.setHorizontalGroup(
            Panel_cajero1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_cajero1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_cajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_cajero1Layout.setVerticalGroup(
            Panel_cajero1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_cajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Base.add(Panel_cajero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        Panel_cajero2.setBackground(new java.awt.Color(64, 153, 167));
        Panel_cajero2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_cajero2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_cajero2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_cajero2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_cajero2MouseExited(evt);
            }
        });

        txt_cajero2.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        txt_cajero2.setForeground(new java.awt.Color(255, 255, 255));
        txt_cajero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_cajero2.setText("Cajero 2");

        javax.swing.GroupLayout Panel_cajero2Layout = new javax.swing.GroupLayout(Panel_cajero2);
        Panel_cajero2.setLayout(Panel_cajero2Layout);
        Panel_cajero2Layout.setHorizontalGroup(
            Panel_cajero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(Panel_cajero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_cajero2Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(txt_cajero2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        Panel_cajero2Layout.setVerticalGroup(
            Panel_cajero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(Panel_cajero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txt_cajero2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        Base.add(Panel_cajero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 210, 50));

        Panel_cajero3.setBackground(new java.awt.Color(64, 153, 167));
        Panel_cajero3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_cajero3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_cajero3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_cajero3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_cajero3MouseExited(evt);
            }
        });

        txt_cajero3.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        txt_cajero3.setForeground(new java.awt.Color(255, 255, 255));
        txt_cajero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_cajero3.setText("Cajero 3");

        javax.swing.GroupLayout Panel_cajero3Layout = new javax.swing.GroupLayout(Panel_cajero3);
        Panel_cajero3.setLayout(Panel_cajero3Layout);
        Panel_cajero3Layout.setHorizontalGroup(
            Panel_cajero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_cajero3Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(txt_cajero3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_cajero3Layout.setVerticalGroup(
            Panel_cajero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_cajero3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Base.add(Panel_cajero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 210, 50));

        add(Base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        Body.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        jLabel1.setText("Elija un cajero");

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(145, 145, 145))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 620, 480));
    }// </editor-fold>//GEN-END:initComponents
// Método que se activa al hacer clic en el panel asociado a la información de Emma
    private void Panel_cajero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cajero1MouseClicked
        // Muestra la información del paciente Emma
        mostrar_panel(new cajero1());
    }//GEN-LAST:event_Panel_cajero1MouseClicked
// Método que se activa al pasar el mouse sobre el panel de Emma
    private void Panel_cajero1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cajero1MouseEntered
        // Cambia el color de fondo del panel cuando el mouse se sitúa sobre él
        Color color1 = new Color (64,130,142);
        Panel_cajero1.setBackground(color1);
    }//GEN-LAST:event_Panel_cajero1MouseEntered
// Método que se activa al salir el mouse del área del panel de Emma
    private void Panel_cajero1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cajero1MouseExited
        // Restaura el color de fondo original del panel cuando el mouse sale de él
        Color color2 = new Color (64,153,167);
        Panel_cajero1.setBackground(color2);
    }//GEN-LAST:event_Panel_cajero1MouseExited

// Método que se activa al hacer clic en el panel asociado a la información de Rosa
    private void Panel_cajero2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cajero2MouseClicked
        // Muestra la información del paciente Rosa
        mostrar_panel(new cajero2());
    }//GEN-LAST:event_Panel_cajero2MouseClicked

// Método que se activa al pasar el mouse sobre el panel de Rosa    
    private void Panel_cajero2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cajero2MouseEntered
        // Cambia el color de fondo del panel cuando el mouse se sitúa sobre él
        Color color1 = new Color (64,130,142);
        Panel_cajero2.setBackground(color1);
    }//GEN-LAST:event_Panel_cajero2MouseEntered

    private void Panel_cajero2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cajero2MouseExited
        Color color2 = new Color (64,153,167);
        Panel_cajero2.setBackground(color2);
    }//GEN-LAST:event_Panel_cajero2MouseExited

    private void Panel_cajero3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cajero3MouseClicked
        mostrar_panel(new cajero3());
    }//GEN-LAST:event_Panel_cajero3MouseClicked

    private void Panel_cajero3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cajero3MouseEntered
        Color color1 = new Color (64,130,142);
        Panel_cajero3.setBackground(color1);
    }//GEN-LAST:event_Panel_cajero3MouseEntered

    private void Panel_cajero3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cajero3MouseExited
        Color color2 = new Color (64,153,167);
        Panel_cajero3.setBackground(color2);
    }//GEN-LAST:event_Panel_cajero3MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Panel_cajero1;
    private javax.swing.JPanel Panel_cajero2;
    private javax.swing.JPanel Panel_cajero3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txt_cajero1;
    private javax.swing.JLabel txt_cajero2;
    private javax.swing.JLabel txt_cajero3;
    // End of variables declaration//GEN-END:variables
}
