/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanels;

import java.text.ParseException;
import java.util.ArrayList;
import proyecto.estructura.de.datos.Doctor;
import proyecto.estructura.de.datos.Info_Cuentas;

/**
 *
 * @author Daniel
 */
public class Pacientes extends javax.swing.JPanel {

    
    public Pacientes(String name) throws ParseException {
        setLayout(null); // Establece un diseño nulo (se recomienda utilizar diseños de diseño de Java Swing)
        initComponents();
        for(Doctor persona : Info_Cuentas.getCuentasDoctores())
        {
            if(persona.getNombre().equals(name))
            {
                persona.getPacientes().imprimir(this, panel_pila);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel_scrollbar = new javax.swing.JPanel();
        panel_pila = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panel_pila.setBackground(new java.awt.Color(255, 255, 255));
        panel_pila.setLayout(new javax.swing.BoxLayout(panel_pila, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout panel_scrollbarLayout = new javax.swing.GroupLayout(panel_scrollbar);
        panel_scrollbar.setLayout(panel_scrollbarLayout);
        panel_scrollbarLayout.setHorizontalGroup(
            panel_scrollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pila, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        panel_scrollbarLayout.setVerticalGroup(
            panel_scrollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pila, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel_scrollbar);

        titulo.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Pacientes actuales");
        titulo.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_pila;
    private javax.swing.JPanel panel_scrollbar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
