/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanels;

import java.text.ParseException;
import java.util.ArrayList;
import proyecto.estructura.de.datos.Info_Cuentas;

/**
 *
 * @author Daniel
 */
public class ver_asegurados_en_cola extends javax.swing.JPanel {

    /**
     * Constructor de la clase que muestra citas.
     * @param nombre Nombre del usuario actual.
     * @param posicion Posición del usuario ("doctor" o "paciente").
     * @throws ParseException Excepción lanzada si ocurre un error al analizar una fecha.
     */
    public ver_asegurados_en_cola() throws ParseException {
        setLayout(null); // Establece un diseño nulo (se recomienda utilizar diseños de diseño de Java Swing)
        initComponents();
        Info_Cuentas.getFila().mostrarCola(this, panel_cola);
        if(cajero1.getAsegurado() != null)
        {
            label_cajero1.setText("Cajero 1: " + cajero1.getAsegurado().getCedula());
        }
        else
        {
            label_cajero1.setText("Cajero 1: Desocupado");
        }
        if(cajero2.getAsegurado() != null)
        {
            label_cajero2.setText("Cajero 2: " + cajero2.getAsegurado().getCedula());
        }
        else
        {
            label_cajero2.setText("Cajero 2: Desocupado");
        }
        if(cajero3.getAsegurado() != null)
        {
            label_cajero3.setText("Cajero 3: " + cajero3.getAsegurado().getCedula());
        }
        else
        {
            label_cajero3.setText("Cajero 3: Desocupado");
        }
        label_total2.setText("atendidos: " + Info_Cuentas.getTotal_atendidos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel_scrollbar = new javax.swing.JPanel();
        panel_cola = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        label_cajero2 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        label_cajero1 = new javax.swing.JLabel();
        label_cajero3 = new javax.swing.JLabel();
        label_total = new javax.swing.JLabel();
        label_total2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panel_cola.setBackground(new java.awt.Color(255, 255, 255));
        panel_cola.setLayout(new javax.swing.BoxLayout(panel_cola, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout panel_scrollbarLayout = new javax.swing.GroupLayout(panel_scrollbar);
        panel_scrollbar.setLayout(panel_scrollbarLayout);
        panel_scrollbarLayout.setHorizontalGroup(
            panel_scrollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_scrollbarLayout.createSequentialGroup()
                .addComponent(panel_cola, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 296, Short.MAX_VALUE))
        );
        panel_scrollbarLayout.setVerticalGroup(
            panel_scrollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_cola, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel_scrollbar);

        titulo.setFont(new java.awt.Font("Roboto Black", 1, 28)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Asegurados en cola");
        titulo.setToolTipText("");

        label_cajero2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        label_cajero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_cajero2.setText("Cajero 2");
        label_cajero2.setToolTipText("");

        titulo2.setFont(new java.awt.Font("Roboto Black", 1, 28)); // NOI18N
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("Asegurados en cajero");
        titulo2.setToolTipText("");

        label_cajero1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        label_cajero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_cajero1.setText("Cajero 1");
        label_cajero1.setToolTipText("");

        label_cajero3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        label_cajero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_cajero3.setText("Cajero 3");
        label_cajero3.setToolTipText("");

        label_total.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        label_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_total.setText("Total de asegurados");
        label_total.setToolTipText("");

        label_total2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        label_total2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_total2.setText("atendidos:");
        label_total2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cajero2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cajero3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_total, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_total2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(titulo2)
                        .addGap(47, 47, 47)
                        .addComponent(label_cajero1)
                        .addGap(35, 35, 35)
                        .addComponent(label_cajero2)
                        .addGap(34, 34, 34)
                        .addComponent(label_cajero3)
                        .addGap(45, 45, 45)
                        .addComponent(label_total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_total2)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_cajero1;
    private javax.swing.JLabel label_cajero2;
    private javax.swing.JLabel label_cajero3;
    private javax.swing.JLabel label_total;
    private javax.swing.JLabel label_total2;
    private javax.swing.JPanel panel_cola;
    private javax.swing.JPanel panel_scrollbar;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
