/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanels;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import proyecto.estructura.de.datos.Empleado;
import proyecto.estructura.de.datos.Info_Cuentas;

/**
 *
 * @author Daniel
 */
public class ver_datos_empleados extends javax.swing.JPanel {
    
    // Variable para almacenar el nombre del doctor
    private String nombre;

    /**
     * Constructor de la clase para ver los datos del doctor.
     * @param NOMBRE Nombre del doctor.
     */
    public ver_datos_empleados(String NOMBRE) {
        initComponents();
        this.nombre = NOMBRE;
        
        // Recorre la lista de cuentas para encontrar al empleado con el nombre proporcionado
        for (Empleado persona : Info_Cuentas.getCuentasEmpleados()) {
            if(nombre.equals(persona.getNombre())) {
                // Muestra los datos del doctor en los componentes de la interfaz gráfica
                Label_nombre.setText("Nombre: " + nombre);
                Label_contraseña.setText(persona.getContraseña());
                Label_tipoEmpleado.setText(persona.getTipoEmpleado()); 
                Label_cedula.setText("Tipo de empleado: " + persona.getCedula());
                Label_observaciones.setText(persona.getObservaciones()); 
                Label_estado.setText(persona.getEstado()); 
            }
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titulo = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        Label_contraseña = new javax.swing.JLabel();
        Label_cedula = new javax.swing.JLabel();
        Label_tipoEmpleado = new javax.swing.JLabel();
        Label_observaciones = new javax.swing.JLabel();
        Label_estado = new javax.swing.JLabel();
        error_contraseña = new javax.swing.JLabel();
        error_cedula = new javax.swing.JLabel();
        error_edad = new javax.swing.JLabel();
        error_pais = new javax.swing.JLabel();
        Label_nombre = new javax.swing.JLabel();
        info_editada = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(620, 530));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_titulo.setText("Perfil");
        label_titulo.setToolTipText("");
        add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 350, -1));

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_contraseña.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_contraseña.setText("Contraseña: ");
        main_panel.add(Label_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        Label_cedula.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_cedula.setText("Cedula:");
        main_panel.add(Label_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        Label_tipoEmpleado.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_tipoEmpleado.setText("Tipo Empleado:");
        main_panel.add(Label_tipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        Label_observaciones.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_observaciones.setText("Observaciones:");
        main_panel.add(Label_observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        Label_estado.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_estado.setText("Estado:");
        main_panel.add(Label_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        error_contraseña.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        error_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        error_contraseña.setText("La contraseña debe tener entre 5 y 20 caracteres");
        main_panel.add(error_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        error_cedula.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        error_cedula.setForeground(new java.awt.Color(255, 255, 255));
        error_cedula.setText("La cedula debe tener 9 caracteres");
        main_panel.add(error_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        error_edad.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        error_edad.setForeground(new java.awt.Color(255, 255, 255));
        error_edad.setText("La edad debe ser mayor a 1 y menor a 123");
        main_panel.add(error_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        error_pais.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        error_pais.setForeground(new java.awt.Color(255, 255, 255));
        error_pais.setText("El pais no existe");
        main_panel.add(error_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        Label_nombre.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_nombre.setText("Nombre: ");
        main_panel.add(Label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        info_editada.setBackground(new java.awt.Color(255, 255, 255));
        info_editada.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        info_editada.setForeground(new java.awt.Color(255, 255, 255));
        info_editada.setText("Informacion editada");
        main_panel.add(info_editada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 160, -1));

        add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 490, 370));
    }// </editor-fold>//GEN-END:initComponents

// Este método limita el ingreso de caracteres en un campo de texto a solo dígitos numéricos.
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_cedula;
    private javax.swing.JLabel Label_contraseña;
    private javax.swing.JLabel Label_estado;
    private javax.swing.JLabel Label_nombre;
    private javax.swing.JLabel Label_observaciones;
    private javax.swing.JLabel Label_tipoEmpleado;
    private javax.swing.JLabel error_cedula;
    private javax.swing.JLabel error_contraseña;
    private javax.swing.JLabel error_edad;
    private javax.swing.JLabel error_pais;
    private javax.swing.JLabel info_editada;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JPanel main_panel;
    // End of variables declaration//GEN-END:variables
}
