//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoULACIT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaParqueoEntities : DbContext
    {
        public SistemaParqueoEntities()
            : base("name=SistemaParqueoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bitacora> Bitacora { get; set; }
        public DbSet<Movimiento> Movimiento { get; set; }
        public DbSet<Parqueo> Parqueo { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Tipo_Vehiculo> Tipo_Vehiculo { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Vehiculo> Vehiculo { get; set; }
    }
}
