//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoULACIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Vehiculo
    {
        public Tipo_Vehiculo()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int ID_Tipo { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
