//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseño_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividades_Itinerario
    {
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha_actividad { get; set; }
        public decimal Destinos_IdDestino { get; set; }
        public decimal Actividades_Destino_IdActividad { get; set; }
        public decimal Itinerarios_IdItinerario { get; set; }
    
        public virtual Actividades_Destino Actividades_Destino { get; set; }
        public virtual Destinos Destinos { get; set; }
        public virtual Itinerarios Itinerarios { get; set; }
    }
}
