//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseño_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Proyecto_Final_Diseño_WebEntities : DbContext
    {
        public Proyecto_Final_Diseño_WebEntities()
            : base("name=Proyecto_Final_Diseño_WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actividades_Destino> Actividades_Destino { get; set; }
        public DbSet<Descuentos> Descuentos { get; set; }
        public DbSet<Destinos> Destinos { get; set; }
        public DbSet<Itinerarios> Itinerarios { get; set; }
        public DbSet<Paquetes_de_viaje> Paquetes_de_viaje { get; set; }
        public DbSet<Reseñas> Reseñas { get; set; }
        public DbSet<Reservas> Reservas { get; set; }
        public DbSet<Tarjetas> Tarjetas { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Actividades_Itinerario> Actividades_Itinerario { get; set; }
        public DbSet<Actividades_Paquete> Actividades_Paquete { get; set; }
    
        public virtual int DeleteActividadesItinerario(Nullable<decimal> destinos_IdDestino, Nullable<decimal> actividades_Destino_IdActividad, Nullable<decimal> itinerarios_IdItinerario)
        {
            var destinos_IdDestinoParameter = destinos_IdDestino.HasValue ?
                new ObjectParameter("Destinos_IdDestino", destinos_IdDestino) :
                new ObjectParameter("Destinos_IdDestino", typeof(decimal));
    
            var actividades_Destino_IdActividadParameter = actividades_Destino_IdActividad.HasValue ?
                new ObjectParameter("Actividades_Destino_IdActividad", actividades_Destino_IdActividad) :
                new ObjectParameter("Actividades_Destino_IdActividad", typeof(decimal));
    
            var itinerarios_IdItinerarioParameter = itinerarios_IdItinerario.HasValue ?
                new ObjectParameter("Itinerarios_IdItinerario", itinerarios_IdItinerario) :
                new ObjectParameter("Itinerarios_IdItinerario", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteActividadesItinerario", destinos_IdDestinoParameter, actividades_Destino_IdActividadParameter, itinerarios_IdItinerarioParameter);
        }
    
        public virtual int DeleteActividadesPaquete(Nullable<decimal> paquetes_de_viaje_IdPaquete, Nullable<decimal> actividades_Destino_IdActividad)
        {
            var paquetes_de_viaje_IdPaqueteParameter = paquetes_de_viaje_IdPaquete.HasValue ?
                new ObjectParameter("Paquetes_de_viaje_IdPaquete", paquetes_de_viaje_IdPaquete) :
                new ObjectParameter("Paquetes_de_viaje_IdPaquete", typeof(decimal));
    
            var actividades_Destino_IdActividadParameter = actividades_Destino_IdActividad.HasValue ?
                new ObjectParameter("Actividades_Destino_IdActividad", actividades_Destino_IdActividad) :
                new ObjectParameter("Actividades_Destino_IdActividad", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteActividadesPaquete", paquetes_de_viaje_IdPaqueteParameter, actividades_Destino_IdActividadParameter);
        }
    
        public virtual int InsertActividadesItinerario(string descripcion, Nullable<System.DateTime> fecha_actividad, Nullable<decimal> destinos_IdDestino, Nullable<decimal> actividades_Destino_IdActividad, Nullable<decimal> itinerarios_IdItinerario)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var fecha_actividadParameter = fecha_actividad.HasValue ?
                new ObjectParameter("Fecha_actividad", fecha_actividad) :
                new ObjectParameter("Fecha_actividad", typeof(System.DateTime));
    
            var destinos_IdDestinoParameter = destinos_IdDestino.HasValue ?
                new ObjectParameter("Destinos_IdDestino", destinos_IdDestino) :
                new ObjectParameter("Destinos_IdDestino", typeof(decimal));
    
            var actividades_Destino_IdActividadParameter = actividades_Destino_IdActividad.HasValue ?
                new ObjectParameter("Actividades_Destino_IdActividad", actividades_Destino_IdActividad) :
                new ObjectParameter("Actividades_Destino_IdActividad", typeof(decimal));
    
            var itinerarios_IdItinerarioParameter = itinerarios_IdItinerario.HasValue ?
                new ObjectParameter("Itinerarios_IdItinerario", itinerarios_IdItinerario) :
                new ObjectParameter("Itinerarios_IdItinerario", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertActividadesItinerario", descripcionParameter, fecha_actividadParameter, destinos_IdDestinoParameter, actividades_Destino_IdActividadParameter, itinerarios_IdItinerarioParameter);
        }
    
        public virtual int InsertActividadesPaquete(Nullable<decimal> paquetes_de_viaje_IdPaquete, Nullable<decimal> actividades_Destino_IdActividad, Nullable<int> nulo)
        {
            var paquetes_de_viaje_IdPaqueteParameter = paquetes_de_viaje_IdPaquete.HasValue ?
                new ObjectParameter("Paquetes_de_viaje_IdPaquete", paquetes_de_viaje_IdPaquete) :
                new ObjectParameter("Paquetes_de_viaje_IdPaquete", typeof(decimal));
    
            var actividades_Destino_IdActividadParameter = actividades_Destino_IdActividad.HasValue ?
                new ObjectParameter("Actividades_Destino_IdActividad", actividades_Destino_IdActividad) :
                new ObjectParameter("Actividades_Destino_IdActividad", typeof(decimal));
    
            var nuloParameter = nulo.HasValue ?
                new ObjectParameter("nulo", nulo) :
                new ObjectParameter("nulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertActividadesPaquete", paquetes_de_viaje_IdPaqueteParameter, actividades_Destino_IdActividadParameter, nuloParameter);
        }
    }
}
