//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseño_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquetes_de_viaje
    {
        public Paquetes_de_viaje()
        {
            this.Actividades_Paquete = new HashSet<Actividades_Paquete>();
        }
    
        public decimal IdPaquete { get; set; }
        public string Nombre_del_paquete { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public decimal Destinos_IdDestino { get; set; }
    
        public virtual Destinos Destinos { get; set; }
        public virtual ICollection<Actividades_Paquete> Actividades_Paquete { get; set; }
    }
}
