//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseño_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public decimal IdReserva { get; set; }
        public Nullable<System.DateTime> Fecha_de_inicio { get; set; }
        public Nullable<System.DateTime> Fecha_final { get; set; }
        public string Tipo_de_servicio { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Estado_de_la_reserva { get; set; }
        public decimal Actividades_Destino_IdActividad { get; set; }
        public decimal Usuarios_Id { get; set; }
    
        public virtual Actividades_Destino Actividades_Destino { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
