//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseño_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjetas
    {
        public decimal IdTarjeta { get; set; }
        public decimal Numero_de_tarjeta { get; set; }
        public System.DateTime Fecha_de_vencimiento { get; set; }
        public decimal Codigo_de_seguridad { get; set; }
        public decimal Usuarios_Id { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
