/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import JPanels.Fila;
import JPanels.ver_asegurados_en_cola;
import JPanels.ver_datos_empleados;
import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Image;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.WindowConstants;
import proyecto.estructura.de.datos.Asegurado;

/**
 *
 * @author dylanrojas
 */
public class menu_asegurados extends javax.swing.JFrame {
    
    // Variables para el manejo de arrastre de la ventana
    int xMouse;
    int yMouse;
    
    // Variable para almacenar el nombre del paciente
    private String cedula;
    private Asegurado asegurado;


    public menu_asegurados(String cedula, Asegurado asegurado) {
        initComponents();
        this.setLocationRelativeTo(this); // Centra la ventana en la pantalla
        this.cedula = cedula; // Asigna el nombre del paciente
        this.asegurado = asegurado;
        mostrar_panel(new Fila(asegurado, Body));
        
        // Se establecen las imágenes a los distintos elementos visuales de la interfaz
        SetImageLabel(Logo, "src\\Imagenes\\Imagen menu principal_Logo.png");
        SetImageLabel(img_minimizar, "src\\Imagenes\\-.png");
        SetImageLabel(img_cerrar, "src\\Imagenes\\x.png");
        SetImageLabel(Profile, "src\\Imagenes\\Profile.png");
        SetImageLabel(Logout, "src\\Imagenes\\Logout.png");
    }
    
    /**
     * Inicializa la ventana del menú de asegurados.
     */
    public void initialize()
    {
        setTitle("Menu Pacientes"); // Establece el título de la ventana
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE); // Define el cierre al cerrar la ventana
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setVisible(true); // Hace visible la ventana
    }
    
    /**
     * Método para mostrar un panel específico en el cuerpo principal del menú.
     *
     * @param frame Componente a mostrar en el cuerpo principal.
     */
    public void mostrar_panel(Component frame)
    {
        frame.setSize(620, 530); // Establece el tamaño del componente
        frame.setLocation(0, 0); // Establece la posición del componente
        Body.removeAll(); // Elimina todos los componentes del cuerpo principal
        Body.add(frame); // Agrega el componente proporcionado al cuerpo principal
        Body.revalidate(); // Revalida el cuerpo principal
        Body.repaint(); // Repinta el cuerpo principal
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Menu_panel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Label_titulo = new javax.swing.JLabel();
        Panel_Menu = new javax.swing.JPanel();
        Panel_fila = new javax.swing.JPanel();
        Label_fila = new javax.swing.JLabel();
        Panel_info_fila = new javax.swing.JPanel();
        info_fila_Label = new javax.swing.JLabel();
        Hospital_name = new javax.swing.JLabel();
        Manu_Separation = new javax.swing.JPanel();
        Profile_Panel = new javax.swing.JPanel();
        Profile = new javax.swing.JLabel();
        Logout_Panel = new javax.swing.JPanel();
        Logout = new javax.swing.JLabel();
        Panel_arriba = new javax.swing.JPanel();
        img_minimizar = new javax.swing.JLabel();
        img_cerrar = new javax.swing.JLabel();
        Cursor_drag = new javax.swing.JTextField();
        Header_panel = new javax.swing.JPanel();
        Body = new javax.swing.JPanel();

        Main_panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Main_panelLayout = new javax.swing.GroupLayout(Main_panel);
        Main_panel.setLayout(Main_panelLayout);
        Main_panelLayout.setHorizontalGroup(
            Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        Main_panelLayout.setVerticalGroup(
            Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu_panel.setBackground(new java.awt.Color(64, 157, 204));
        Menu_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen menu principal_Logo.png"))); // NOI18N
        Menu_panel.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 77, 51, 48));

        Label_titulo.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        Label_titulo.setForeground(new java.awt.Color(255, 255, 255));
        Label_titulo.setText("MENU ASEGURADOS");
        Menu_panel.add(Label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 48));

        Panel_Menu.setBackground(new java.awt.Color(64, 153, 167));

        Panel_fila.setBackground(new java.awt.Color(64, 153, 167));
        Panel_fila.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_fila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_filaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_filaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_filaMouseExited(evt);
            }
        });

        Label_fila.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Label_fila.setForeground(new java.awt.Color(255, 255, 255));
        Label_fila.setText("Fila");

        javax.swing.GroupLayout Panel_filaLayout = new javax.swing.GroupLayout(Panel_fila);
        Panel_fila.setLayout(Panel_filaLayout);
        Panel_filaLayout.setHorizontalGroup(
            Panel_filaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_filaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Label_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        Panel_filaLayout.setVerticalGroup(
            Panel_filaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_fila, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        Panel_info_fila.setBackground(new java.awt.Color(64, 153, 167));
        Panel_info_fila.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_info_fila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_info_filaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_info_filaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_info_filaMouseExited(evt);
            }
        });

        info_fila_Label.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        info_fila_Label.setForeground(new java.awt.Color(255, 255, 255));
        info_fila_Label.setText("Informacion de Fila");

        javax.swing.GroupLayout Panel_info_filaLayout = new javax.swing.GroupLayout(Panel_info_fila);
        Panel_info_fila.setLayout(Panel_info_filaLayout);
        Panel_info_filaLayout.setHorizontalGroup(
            Panel_info_filaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_info_filaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(info_fila_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel_info_filaLayout.setVerticalGroup(
            Panel_info_filaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(info_fila_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel_MenuLayout = new javax.swing.GroupLayout(Panel_Menu);
        Panel_Menu.setLayout(Panel_MenuLayout);
        Panel_MenuLayout.setHorizontalGroup(
            Panel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_fila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_info_fila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel_MenuLayout.setVerticalGroup(
            Panel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MenuLayout.createSequentialGroup()
                .addComponent(Panel_fila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_info_fila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu_panel.add(Panel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 158, 282, 150));

        Hospital_name.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Hospital_name.setForeground(new java.awt.Color(255, 255, 255));
        Hospital_name.setText("SEGUROS ULACIT");
        Menu_panel.add(Hospital_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        Manu_Separation.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Manu_SeparationLayout = new javax.swing.GroupLayout(Manu_Separation);
        Manu_Separation.setLayout(Manu_SeparationLayout);
        Manu_SeparationLayout.setHorizontalGroup(
            Manu_SeparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Manu_SeparationLayout.setVerticalGroup(
            Manu_SeparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        Menu_panel.add(Manu_Separation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 282, -1));

        Profile_Panel.setBackground(new java.awt.Color(64, 157, 204));

        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Profile.png"))); // NOI18N
        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProfileMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Profile_PanelLayout = new javax.swing.GroupLayout(Profile_Panel);
        Profile_Panel.setLayout(Profile_PanelLayout);
        Profile_PanelLayout.setHorizontalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE)
        );
        Profile_PanelLayout.setVerticalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        Menu_panel.add(Profile_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 51, 50));

        Logout_Panel.setBackground(new java.awt.Color(64, 157, 204));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logout.png"))); // NOI18N
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Logout_PanelLayout = new javax.swing.GroupLayout(Logout_Panel);
        Logout_Panel.setLayout(Logout_PanelLayout);
        Logout_PanelLayout.setHorizontalGroup(
            Logout_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Logout_PanelLayout.createSequentialGroup()
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );
        Logout_PanelLayout.setVerticalGroup(
            Logout_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        Menu_panel.add(Logout_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 50, 50));

        jPanel2.add(Menu_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 570));

        Panel_arriba.setBackground(new java.awt.Color(64, 130, 142));

        img_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-.png"))); // NOI18N
        img_minimizar.setText("jLabel1");
        img_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_minimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_minimizarMouseExited(evt);
            }
        });

        img_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png"))); // NOI18N
        img_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_cerrarMouseExited(evt);
            }
        });

        Cursor_drag.setEditable(false);
        Cursor_drag.setBackground(new java.awt.Color(64, 130, 142));
        Cursor_drag.setForeground(new java.awt.Color(255, 255, 255));
        Cursor_drag.setBorder(null);
        Cursor_drag.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout Panel_arribaLayout = new javax.swing.GroupLayout(Panel_arriba);
        Panel_arriba.setLayout(Panel_arribaLayout);
        Panel_arribaLayout.setHorizontalGroup(
            Panel_arribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_arribaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Cursor_drag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 463, Short.MAX_VALUE)
                .addComponent(img_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(img_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        Panel_arribaLayout.setVerticalGroup(
            Panel_arribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_arribaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_arribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(img_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cursor_drag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.add(Panel_arriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 620, 40));

        Header_panel.setBackground(new java.awt.Color(64, 157, 204));
        Header_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Header_panelMouseDragged(evt);
            }
        });
        Header_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Header_panelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Header_panelLayout = new javax.swing.GroupLayout(Header_panel);
        Header_panel.setLayout(Header_panelLayout);
        Header_panelLayout.setHorizontalGroup(
            Header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        Header_panelLayout.setVerticalGroup(
            Header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(Header_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        Body.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel2.add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 620, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void img_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_minimizarMouseClicked
        setState(Frame.ICONIFIED); // Minimiza la ventana al hacer clic en el botón de minimizar
    }//GEN-LAST:event_img_minimizarMouseClicked

    private void img_minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_minimizarMouseEntered
        // Cambia el icono del botón de minimizar al pasar el mouse sobre él
        img_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-_hover.png")));
        SetImageLabel(img_minimizar, "src\\Imagenes\\-_hover.png");
    }//GEN-LAST:event_img_minimizarMouseEntered

    private void img_minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_minimizarMouseExited
        // Restaura el icono original del botón de minimizar al quitar el mouse
        img_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-.png")));
        SetImageLabel(img_minimizar, "src\\Imagenes\\-.png");
    }//GEN-LAST:event_img_minimizarMouseExited

    private void Header_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Header_panelMousePressed
        // Guarda las coordenadas del clic del mouse en el panel de encabezado
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Header_panelMousePressed

    private void Header_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Header_panelMouseDragged
        // Actualiza la ubicación de la ventana mientras se arrastra con el mouse
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Header_panelMouseDragged

    private void img_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_cerrarMouseClicked
        // Sale de la aplicación al hacer clic en el botón de cerrar
        System.exit(0);
    }//GEN-LAST:event_img_cerrarMouseClicked

    private void img_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_cerrarMouseEntered
        // Eventos de entrada y salida del mouse para el panel de citas
        img_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x_hover.png")));
        SetImageLabel(img_cerrar, "src\\Imagenes\\x_hover.png");
    }//GEN-LAST:event_img_cerrarMouseEntered

    private void img_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_cerrarMouseExited
        img_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png")));
        SetImageLabel(img_cerrar, "src\\Imagenes\\x.png");
    }//GEN-LAST:event_img_cerrarMouseExited

    private void Panel_filaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_filaMouseEntered
        Color color1 = new Color (64,130,142);
        Panel_fila.setBackground(color1);
    }//GEN-LAST:event_Panel_filaMouseEntered

    private void Panel_filaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_filaMouseExited
        Color color2 = new Color (64,153,167);
        Panel_fila.setBackground(color2);
    }//GEN-LAST:event_Panel_filaMouseExited

    private void Panel_filaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_filaMouseClicked
        mostrar_panel(new Fila(asegurado, Body));
    }//GEN-LAST:event_Panel_filaMouseClicked

    private void Panel_info_filaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_info_filaMouseClicked
        try {
            mostrar_panel(new ver_asegurados_en_cola());
        } catch (ParseException ex) {
            Logger.getLogger(menu_asegurados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Panel_info_filaMouseClicked

    // Eventos de entrada y salida del mouse para el botón de perfil
    private void Panel_info_filaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_info_filaMouseEntered
        Color color1 = new Color (64,130,142);
        Panel_info_fila.setBackground(color1);
    }//GEN-LAST:event_Panel_info_filaMouseEntered

    private void Panel_info_filaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_info_filaMouseExited
        Color color2 = new Color (64,153,167);
        Panel_info_fila.setBackground(color2);
    }//GEN-LAST:event_Panel_info_filaMouseExited

    private void ProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseEntered
        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Profile_hover.png")));
        SetImageLabel(Profile, "src\\Imagenes\\Profile_hover.png");
    }//GEN-LAST:event_ProfileMouseEntered

    private void ProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseExited
        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Profile.png")));
        SetImageLabel(Profile, "src\\Imagenes\\Profile.png");
    }//GEN-LAST:event_ProfileMouseExited

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
        mostrar_panel(new ver_datos_empleados(this.cedula));
    }//GEN-LAST:event_ProfileMouseClicked

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logout_hover.png")));
        SetImageLabel(Logout, "src\\Imagenes\\Logout_hover.png");
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logout.png")));
        SetImageLabel(Logout, "src\\Imagenes\\Logout.png");
    }//GEN-LAST:event_LogoutMouseExited

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        Inicio_Sesion menu_principal = new Inicio_Sesion();
        menu_principal.initialize();
        dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void SetImageLabel(JLabel labelName, String root) {
    // Carga la imagen desde la ruta y la establece en el JLabel
    ImageIcon image = new ImageIcon(root);
    Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
    labelName.setIcon(icon);
    this.repaint(); // Vuelve a pintar la ventana para mostrar el cambio de imagen
}

public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* Si Nimbus (introducido en Java SE 6) no está disponible, se utiliza la apariencia predeterminada.
     * Para más detalles, consulta http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(menu_asegurados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(menu_asegurados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(menu_asegurados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(menu_asegurados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Crea y muestra el formulario */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Crea una nueva instancia de menu_pacientes y la hace visible
            new menu_asegurados(null,null).setVisible(true);
        }
    });
}

public String getCedula() {
    return cedula; // Devuelve el nombre almacenado en la variable "name"
}

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JTextField Cursor_drag;
    private javax.swing.JPanel Header_panel;
    private javax.swing.JLabel Hospital_name;
    private javax.swing.JLabel Label_fila;
    private javax.swing.JLabel Label_titulo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logout;
    private javax.swing.JPanel Logout_Panel;
    private javax.swing.JPanel Main_panel;
    private javax.swing.JPanel Manu_Separation;
    private javax.swing.JPanel Menu_panel;
    private javax.swing.JPanel Panel_Menu;
    private javax.swing.JPanel Panel_arriba;
    private javax.swing.JPanel Panel_fila;
    private javax.swing.JPanel Panel_info_fila;
    private javax.swing.JLabel Profile;
    private javax.swing.JPanel Profile_Panel;
    private javax.swing.JLabel img_cerrar;
    private javax.swing.JLabel img_minimizar;
    private javax.swing.JLabel info_fila_Label;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
