package cliente_proyecto_final_programacion_concurrente;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.WindowConstants;


public class InterfazCliente extends javax.swing.JFrame {

    private static String bus;
    
    public InterfazCliente() {
        setLayout(null); // Establece un diseño nulo (se recomienda utilizar diseños de diseño de Java Swing)
        initComponents();
        this.bus = buses_combobox.getSelectedItem().toString(); // Le pone el valor a la variable del bus dependiendo de lo que haya en el combobox
        // Verifica cual bus esta seleccionado para mostrar las paradas
        if (bus.equals("bus 1")) {
            // Recorre las paradas que hayan disponibles
            for (String parada : Paradas.getListabus1()) {
                JLabel parada1 = new JLabel(); //crea un jlabel
                parada1.setText(parada); //le cambia el texto a la parada
                panel_paradas.add(parada1); // Agrega la parada al panel
                panel_paradas.repaint(); // Actualiza la representación visual del panel
                panel_paradas.revalidate(); // Revalida el panel para que se muestren los cambios
            }
        }
    }
    
    public void initialize()
    {
        //Inizializa la ventana
        setTitle("Cliente");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    //-------------------------GETTERS Y SETTERS----------------------------------
    public static String getBus() {
        return bus;
    }

    public void setBus(String bus) {
        InterfazCliente.bus = bus;
    }

    public static JPanel getPanel_paradas() {
        return panel_paradas;
    }

    public void setPanel_paradas(JPanel panel_paradas) {
        InterfazCliente.panel_paradas = panel_paradas;
    }
    //---------------------------------------------------------------------------------
    public void borrar_todo()
    {
        //borra todo lo que haya en el panel
        panel_paradas.removeAll(); // Elimina todos los componentes del cuerpo principal
        panel_paradas.revalidate(); // Revalida el cuerpo principal
        panel_paradas.repaint(); // Repinta el cuerpo principal
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel_scrollbar = new javax.swing.JPanel();
        panel_paradas = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        buses_combobox = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_paradas.setBackground(new java.awt.Color(255, 255, 255));
        panel_paradas.setLayout(new javax.swing.BoxLayout(panel_paradas, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout panel_scrollbarLayout = new javax.swing.GroupLayout(panel_scrollbar);
        panel_scrollbar.setLayout(panel_scrollbarLayout);
        panel_scrollbarLayout.setHorizontalGroup(
            panel_scrollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_paradas, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        panel_scrollbarLayout.setVerticalGroup(
            panel_scrollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_paradas, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel_scrollbar);

        titulo.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Paradas");
        titulo.setToolTipText("");

        buses_combobox.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        buses_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bus 1", "bus 2", "bus 3", "bus 4", "bus 5", "bus 6", "bus 7", "bus 8", "bus 9", "bus 10" }));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(135, 135, 135)
                        .addComponent(buses_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAceptar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(buses_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        borrar_todo(); //Borra todo lo que hay en el pannel
        this.bus = buses_combobox.getSelectedItem().toString();
        // Verifica cual bus esta seleccionado para mostrar las paradas
        if (bus.equals("bus 1")) {
            // Recorre las paradas que hayan disponibles
            for (String parada : Paradas.getListabus1()) {
                JLabel parada1 = new JLabel();
                parada1.setText(parada);
                panel_paradas.add(parada1);
                panel_paradas.repaint();
                panel_paradas.revalidate();
            }
        }
        // Verifica cual bus esta seleccionado para mostrar las paradas
        else if (bus.equals("bus 2")) {
            // Recorre las paradas que hayan disponibles
            for (String parada : Paradas.getListabus2()) {
                JLabel parada1 = new JLabel();
                parada1.setText(parada);
                panel_paradas.add(parada1);
                panel_paradas.repaint();
                panel_paradas.revalidate();
            }
        }
        // Verifica cual bus esta seleccionado para mostrar las paradas
        else if (bus.equals("bus 3")) {
            // Recorre las paradas que hayan disponibles
            for (String parada : Paradas.getListabus3()) {
                JLabel parada1 = new JLabel();
                parada1.setText(parada);
                panel_paradas.add(parada1);
                panel_paradas.repaint();
                panel_paradas.revalidate();
            }
        }
        // Verifica cual bus esta seleccionado para mostrar las paradas
        else if (bus.equals("bus 4")) {
            // Recorre las paradas que hayan disponibles
            for (String parada : Paradas.getListabus4()) {
                JLabel parada1 = new JLabel();
                parada1.setText(parada);
                panel_paradas.add(parada1);
                panel_paradas.repaint();
                panel_paradas.revalidate();
            }
        }
        // Verifica cual bus esta seleccionado para mostrar las paradas
        else if (bus.equals("bus 5")) {
            // Recorre las paradas que hayan disponibles
            for (String parada : Paradas.getListabus5()) {
                JLabel parada1 = new JLabel();
                parada1.setText(parada);
                panel_paradas.add(parada1);
                panel_paradas.repaint();
                panel_paradas.revalidate();
            }
        }
        // Verifica cual bus esta seleccionado para mostrar las paradas
        else if (bus.equals("bus 6")) {
            // Recorre las paradas que hayan disponibles
            for (String parada : Paradas.getListabus6()) {
                JLabel parada1 = new JLabel();
                parada1.setText(parada);
                panel_paradas.add(parada1);
                panel_paradas.repaint(); 
                panel_paradas.revalidate(); 
            }
        }
        // Verifica cual bus esta seleccionado para mostrar las paradas
        else if (bus.equals("bus 7")) {
            // Recorre las paradas que hayan disponibles
            for (String parada : Paradas.getListabus7()) {
                JLabel parada1 = new JLabel();
                parada1.setText(parada);
                panel_paradas.add(parada1); 
                panel_paradas.repaint(); 
                panel_paradas.revalidate(); 
            }
        }
        // Verifica cual bus esta seleccionado para mostrar las paradas
        else if (bus.equals("bus 8")) {
            // Recorre las paradas que hayan disponibles
            for (String parada : Paradas.getListabus8()) {
                JLabel parada1 = new JLabel();
                parada1.setText(parada);
                panel_paradas.add(parada1); 
                panel_paradas.repaint(); 
                panel_paradas.revalidate(); 
            }
        }
        // Verifica cual bus esta seleccionado para mostrar las paradas
        else if (bus.equals("bus 9")) {
            // Recorre las paradas que hayan disponibles
            for (String parada : Paradas.getListabus9()) {
                JLabel parada1 = new JLabel();
                parada1.setText(parada);
                panel_paradas.add(parada1); 
                panel_paradas.repaint(); 
                panel_paradas.revalidate(); 
            }
        }
        // Verifica cual bus esta seleccionado para mostrar las paradas
        else if (bus.equals("bus 10")) {
            // Recorre las paradas que hayan disponibles
            for (String parada : Paradas.getListabus10()) {
                JLabel parada1 = new JLabel();
                parada1.setText(parada);
                panel_paradas.add(parada1); 
                panel_paradas.repaint(); 
                panel_paradas.revalidate(); 
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> buses_combobox;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JPanel panel_paradas;
    private javax.swing.JPanel panel_scrollbar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
