//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseño_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuentos
    {
        public decimal IdDescuento { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public decimal Actividades_Destino_IdActividad { get; set; }
    
        public virtual Actividades_Destino Actividades_Destino { get; set; }
    }
}
