//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseño_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destinos
    {
        public Destinos()
        {
            this.Actividades_Destino = new HashSet<Actividades_Destino>();
            this.Actividades_Itinerario = new HashSet<Actividades_Itinerario>();
            this.Paquetes_de_viaje = new HashSet<Paquetes_de_viaje>();
            this.Reseñas = new HashSet<Reseñas>();
        }
    
        public decimal IdDestino { get; set; }
        public string Nombre { get; set; }
        public string Provincia { get; set; }
        public string Categoria { get; set; }
        public Nullable<decimal> Precio_Minimo { get; set; }
        public Nullable<decimal> Precio_Maximo { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual ICollection<Actividades_Destino> Actividades_Destino { get; set; }
        public virtual ICollection<Actividades_Itinerario> Actividades_Itinerario { get; set; }
        public virtual ICollection<Paquetes_de_viaje> Paquetes_de_viaje { get; set; }
        public virtual ICollection<Reseñas> Reseñas { get; set; }
    }
}
