//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseño_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reseñas
    {
        public decimal IdReseña { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
        public string Comentario { get; set; }
        public decimal Usuarios_Id { get; set; }
        public decimal Destinos_IdDestino { get; set; }
    
        public virtual Destinos Destinos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
