//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseño_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Itinerarios = new HashSet<Itinerarios>();
            this.Reseñas = new HashSet<Reseñas>();
            this.Reservas = new HashSet<Reservas>();
            this.Tarjetas = new HashSet<Tarjetas>();
        }
    
        public decimal Id { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public Nullable<System.DateTime> Fecha_de_nacimiento { get; set; }
        public string Genero { get; set; }
        public string Rol { get; set; }
        public Nullable<decimal> Telefono { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Nombre_Completo { get; set; }
        public string Preferencias_de_Viaje { get; set; }
    
        public virtual ICollection<Itinerarios> Itinerarios { get; set; }
        public virtual ICollection<Reseñas> Reseñas { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
        public virtual ICollection<Tarjetas> Tarjetas { get; set; }
    }
}
