/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanels;

import JFrames.Inicio_Sesion;
import JFrames.menu_administradores;
import JFrames.menu_doctores;
import JFrames.menu_empleados;
import java.awt.Color;
import java.util.ArrayList;
import proyecto.estructura.de.datos.Doctor;
import proyecto.estructura.de.datos.Empleado;
import proyecto.estructura.de.datos.Info_Cuentas;

/**
 *
 * @author Daniel
 */
public class datos_inicio_sesion extends javax.swing.JPanel {

    private String name;
    private Inicio_Sesion ventana;
    /**
     * Creates new form Iniciar_sesion
     */
    public datos_inicio_sesion(Inicio_Sesion ventana) {
        initComponents();
        this.ventana = ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_usuario = new javax.swing.JLabel();
        Separator_usuario = new javax.swing.JSeparator();
        txt_field_usuario = new javax.swing.JTextField();
        Label_contraseña = new javax.swing.JLabel();
        txt_field_contraseña = new javax.swing.JPasswordField();
        Separator_contraseña = new javax.swing.JSeparator();
        Boton_iniciar_sesion = new javax.swing.JPanel();
        Label_boton_iniciar_sesion = new javax.swing.JLabel();
        Label_datos_incorrectos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        Label_usuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        Label_usuario.setText("USUARIO");

        Separator_usuario.setForeground(new java.awt.Color(0, 0, 0));

        txt_field_usuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txt_field_usuario.setForeground(new java.awt.Color(204, 204, 204));
        txt_field_usuario.setText("Ingrese su nombre de usuario");
        txt_field_usuario.setBorder(null);
        txt_field_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_usuarioMousePressed(evt);
            }
        });

        Label_contraseña.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        Label_contraseña.setText("CONTRASEÑA");

        txt_field_contraseña.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        txt_field_contraseña.setForeground(new java.awt.Color(204, 204, 204));
        txt_field_contraseña.setText("*************");
        txt_field_contraseña.setToolTipText("");
        txt_field_contraseña.setBorder(null);
        txt_field_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_field_contraseñaMousePressed(evt);
            }
        });

        Separator_contraseña.setForeground(new java.awt.Color(0, 0, 0));

        Boton_iniciar_sesion.setBackground(new java.awt.Color(64, 157, 204));

        Label_boton_iniciar_sesion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Label_boton_iniciar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        Label_boton_iniciar_sesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_boton_iniciar_sesion.setText("Iniciar Sesion");
        Label_boton_iniciar_sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_boton_iniciar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Label_boton_iniciar_sesionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Boton_iniciar_sesionLayout = new javax.swing.GroupLayout(Boton_iniciar_sesion);
        Boton_iniciar_sesion.setLayout(Boton_iniciar_sesionLayout);
        Boton_iniciar_sesionLayout.setHorizontalGroup(
            Boton_iniciar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_boton_iniciar_sesion, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        Boton_iniciar_sesionLayout.setVerticalGroup(
            Boton_iniciar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_boton_iniciar_sesion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Label_datos_incorrectos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Label_datos_incorrectos.setForeground(new java.awt.Color(255, 255, 255));
        Label_datos_incorrectos.setText("Usuario y/o contraseña incorrectos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_datos_incorrectos, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_field_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Separator_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_field_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Separator_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_iniciar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txt_field_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Separator_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Label_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txt_field_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Separator_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Label_datos_incorrectos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_iniciar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_field_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_usuarioMousePressed
        Label_datos_incorrectos.setForeground(Color.white);
        if (String.valueOf(txt_field_usuario.getText()).equals("Ingrese su nombre de usuario")) {
            txt_field_usuario.setText("");
            txt_field_usuario.setForeground(Color.black);
        }
        if (String.valueOf(txt_field_contraseña.getPassword()).isEmpty())
        {
            txt_field_contraseña.setText("*************");
            txt_field_contraseña.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txt_field_usuarioMousePressed

    private void txt_field_contraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_field_contraseñaMousePressed
        Label_datos_incorrectos.setForeground(Color.white);
        if (String.valueOf(txt_field_contraseña.getPassword()).equals("*************")) {
            txt_field_contraseña.setText("");
            txt_field_contraseña.setForeground(Color.black);
        }
        if (txt_field_usuario.getText().isEmpty())
        {
            txt_field_usuario.setText("Ingrese su nombre de usuario");
            txt_field_usuario.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txt_field_contraseñaMousePressed

    private void Label_boton_iniciar_sesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_boton_iniciar_sesionMousePressed

        for (Empleado persona : Info_Cuentas.getCuentasEmpleados())
        {
            if (txt_field_usuario.getText().equals(persona.getNombre()) && String.valueOf(txt_field_contraseña.getPassword()).equals(persona.getContraseña()))
            {
                this.name = persona.getCedula();
                menu_empleados menu_empleados = new menu_empleados(this.name);
                menu_empleados.initialize();
                ventana.dispose();
                return;
            }
        }
        if (txt_field_usuario.getText().equals(Info_Cuentas.getAdministrador().getNombre()) && String.valueOf(txt_field_contraseña.getPassword()).equals(Info_Cuentas.getAdministrador().getContraseña()))
            {
                this.name = Info_Cuentas.getAdministrador().getNombre();
                menu_administradores menu_administrador = new menu_administradores(this.name);
                menu_administrador.initialize();
                ventana.dispose();
                return;
            }
        for (Doctor persona : Info_Cuentas.getCuentasDoctores())
        {
            if (txt_field_usuario.getText().equals(persona.getNombre()) && String.valueOf(txt_field_contraseña.getPassword()).equals(persona.getContraseña()))
                {
                    this.name = persona.getNombre();
                    menu_doctores menu_doctores = new menu_doctores(this.name);
                    menu_doctores.initialize();
                    ventana.dispose();
                    return;
                }
        }
        Label_datos_incorrectos.setForeground(Color.red);
    }//GEN-LAST:event_Label_boton_iniciar_sesionMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Boton_iniciar_sesion;
    private javax.swing.JLabel Label_boton_iniciar_sesion;
    private javax.swing.JLabel Label_contraseña;
    private javax.swing.JLabel Label_datos_incorrectos;
    private javax.swing.JLabel Label_usuario;
    private javax.swing.JSeparator Separator_contraseña;
    private javax.swing.JSeparator Separator_usuario;
    private javax.swing.JPasswordField txt_field_contraseña;
    private javax.swing.JTextField txt_field_usuario;
    // End of variables declaration//GEN-END:variables
}
