/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanels;

import java.awt.Color;
import java.text.SimpleDateFormat;
import proyecto.estructura.de.datos.Asegurado;
import proyecto.estructura.de.datos.Info_Cuentas;

/**
 *
 * @author Daniel
 */
public class expediente extends javax.swing.JPanel {

    private Asegurado asegurado;
    public expediente(Asegurado asegurado) {
        initComponents();
        this.asegurado = asegurado;
        txt_cedula.setText("Cedula: " + asegurado.getCedula());
        txt_id_expediente.setText("ID de expediente: " + asegurado.getExpediente().getIdExpediente());
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        String fecha = formatoFecha.format(asegurado.getExpediente().getFecha());
        txt_fecha.setText("Fecha: " + fecha);
        txt_tipo_seguro.setText("Tipo Seguro: " + asegurado.getTipoSeguro().getDescripcionSeguro());
        txt_field_observaciones.setText(asegurado.getExpediente().getObservaciones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_observaciones = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JLabel();
        txt_id_expediente = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JLabel();
        txt_tipo_seguro = new javax.swing.JLabel();
        txt_field_observaciones = new javax.swing.JTextField();
        panel_editar = new javax.swing.JPanel();
        txt_editar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txt_observaciones.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txt_observaciones.setText("Observaciones: ");

        txt_cedula.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txt_cedula.setText("Cedula: ");

        txt_id_expediente.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txt_id_expediente.setText("ID de expediente: ");

        txt_fecha.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txt_fecha.setText("Fecha: ");

        txt_tipo_seguro.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txt_tipo_seguro.setText("Tipo de seguro: ");

        txt_field_observaciones.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N

        panel_editar.setBackground(new java.awt.Color(64, 153, 167));
        panel_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_editarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_editarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_editarMouseExited(evt);
            }
        });

        txt_editar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txt_editar.setForeground(new java.awt.Color(255, 255, 255));
        txt_editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_editar.setText("Hacer Observacion");

        javax.swing.GroupLayout panel_editarLayout = new javax.swing.GroupLayout(panel_editar);
        panel_editar.setLayout(panel_editarLayout);
        panel_editarLayout.setHorizontalGroup(
            panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_editarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_editarLayout.setVerticalGroup(
            panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cedula)
                            .addComponent(txt_id_expediente))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tipo_seguro)
                            .addComponent(txt_fecha)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_observaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_field_observaciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(panel_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cedula)
                    .addComponent(txt_fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_expediente)
                    .addComponent(txt_tipo_seguro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_observaciones)
                    .addComponent(txt_field_observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panel_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_editarMouseClicked
       asegurado.getExpediente().setObservaciones(String.valueOf(txt_field_observaciones.getText()));
    }//GEN-LAST:event_panel_editarMouseClicked

    private void panel_editarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_editarMouseEntered
        Color color1 = new Color (64,130,142);
        panel_editar.setBackground(color1);
    }//GEN-LAST:event_panel_editarMouseEntered

    private void panel_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_editarMouseExited
        Color color2 = new Color (64,153,167);
        panel_editar.setBackground(color2);
    }//GEN-LAST:event_panel_editarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel_editar;
    private javax.swing.JLabel txt_cedula;
    private javax.swing.JLabel txt_editar;
    private javax.swing.JLabel txt_fecha;
    private javax.swing.JTextField txt_field_observaciones;
    private javax.swing.JLabel txt_id_expediente;
    private javax.swing.JLabel txt_observaciones;
    private javax.swing.JLabel txt_tipo_seguro;
    // End of variables declaration//GEN-END:variables
}
