//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace_Zapatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public Administrador()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int IdAdministrador { get; set; }
        public string Correo { get; set; }
        public string Nombre { get; set; }
        public string Password { get; set; }
        public int Telefono { get; set; }
        public int Edad { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
