//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace_Zapatos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoDiseñoDeAplicacionesEntities : DbContext
    {
        public ProyectoDiseñoDeAplicacionesEntities()
            : base("name=ProyectoDiseñoDeAplicacionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrador> Administrador { get; set; }
        public DbSet<CarritoDeCompras> CarritoDeCompras { get; set; }
        public DbSet<Carrito_Producto> Carrito_Producto { get; set; }
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<comprador> comprador { get; set; }
        public DbSet<DireccionComprador> DireccionComprador { get; set; }
        public DbSet<DireccionVendedor> DireccionVendedor { get; set; }
        public DbSet<HistorialPedidos> HistorialPedidos { get; set; }
        public DbSet<Marca> Marca { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Producto_Orden> Producto_Orden { get; set; }
        public DbSet<ReviewProducto> ReviewProducto { get; set; }
        public DbSet<ReviewVendedor> ReviewVendedor { get; set; }
        public DbSet<Talla> Talla { get; set; }
        public DbSet<TarjetaCredito> TarjetaCredito { get; set; }
        public DbSet<Vendedor> Vendedor { get; set; }
        public DbSet<Orden> Orden { get; set; }
        public DbSet<Imagenes_Producto> Imagenes_Producto { get; set; }
    }
}
