//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace_Zapatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarritoDeCompras
    {
        public CarritoDeCompras()
        {
            this.Carrito_Producto = new HashSet<Carrito_Producto>();
            this.comprador = new HashSet<comprador>();
        }
    
        public int IdCarrito { get; set; }
        public int Precio { get; set; }
    
        public virtual ICollection<Carrito_Producto> Carrito_Producto { get; set; }
        public virtual ICollection<comprador> comprador { get; set; }
    }
}
