//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace_Zapatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprador
    {
        public comprador()
        {
            this.DireccionComprador = new HashSet<DireccionComprador>();
            this.ReviewProducto = new HashSet<ReviewProducto>();
            this.ReviewVendedor = new HashSet<ReviewVendedor>();
            this.TarjetaCredito = new HashSet<TarjetaCredito>();
            this.Orden = new HashSet<Orden>();
        }
    
        public int IdComprador { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Password { get; set; }
        public int Telefono { get; set; }
        public int Edad { get; set; }
        public int CarritoDeCompras_IdCarrito { get; set; }
    
        public virtual CarritoDeCompras CarritoDeCompras { get; set; }
        public virtual ICollection<DireccionComprador> DireccionComprador { get; set; }
        public virtual ICollection<ReviewProducto> ReviewProducto { get; set; }
        public virtual ICollection<ReviewVendedor> ReviewVendedor { get; set; }
        public virtual ICollection<TarjetaCredito> TarjetaCredito { get; set; }
        public virtual ICollection<Orden> Orden { get; set; }
    }
}
