//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace_Zapatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionVendedor
    {
        public int IdDirrecionVendedor { get; set; }
        public string Pais { get; set; }
        public int CodigoPostal { get; set; }
        public string Descripcion { get; set; }
        public string Ciudad { get; set; }
        public Nullable<int> Vendedor_IdVendedor { get; set; }
    
        public virtual Vendedor Vendedor { get; set; }
    }
}
