//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace_Zapatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialPedidos
    {
        public string Vendedor { get; set; }
        public string DireccionEnvio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string MetodoDePago { get; set; }
        public int Orden_IdOrden { get; set; }
        public int IdHistorial { get; set; }
    
        public virtual Orden Orden { get; set; }
    }
}
