//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace_Zapatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Carrito_Producto = new HashSet<Carrito_Producto>();
            this.Producto_Orden = new HashSet<Producto_Orden>();
            this.ReviewProducto = new HashSet<ReviewProducto>();
        }
    
        public int IdProducto { get; set; }
        public string Modelo { get; set; }
        public int Precio { get; set; }
        public int Stock { get; set; }
        public string Color { get; set; }
        public string Disponibilidad { get; set; }
        public int Vendedor_IdVendedor { get; set; }
        public int Marca_IdMarca { get; set; }
        public int Talla_IdTalla { get; set; }
        public int Categoria_IdCategoria { get; set; }
        public bool Aprobado { get; set; }
        public int Administrador_IdAdministrador { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual ICollection<Carrito_Producto> Carrito_Producto { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Talla Talla { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        public virtual ICollection<Producto_Orden> Producto_Orden { get; set; }
        public virtual ICollection<ReviewProducto> ReviewProducto { get; set; }
        public virtual Imagenes_Producto Imagenes_Producto { get; set; }
    }
}
