//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace_Zapatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewProducto
    {
        public int IdReviewProducto { get; set; }
        public string Comentario { get; set; }
        public int Calificacion { get; set; }
        public int comprador_IdComprador { get; set; }
        public int Producto_IdProducto { get; set; }
    
        public virtual comprador comprador { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
