//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace_Zapatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talla
    {
        public Talla()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int IdTalla { get; set; }
        public int Numero { get; set; }
        public string TipoTalla { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
