//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace_Zapatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        public Vendedor()
        {
            this.DireccionVendedor = new HashSet<DireccionVendedor>();
            this.Producto = new HashSet<Producto>();
            this.ReviewVendedor = new HashSet<ReviewVendedor>();
            this.Orden = new HashSet<Orden>();
        }
    
        public int IdVendedor { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Password { get; set; }
        public int Telefono { get; set; }
        public int Edad { get; set; }
    
        public virtual ICollection<DireccionVendedor> DireccionVendedor { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<ReviewVendedor> ReviewVendedor { get; set; }
        public virtual ICollection<Orden> Orden { get; set; }
    }
}
